### ISSUE TITLE
Stray crashes on launch on Skylake NUC NUC6i5SYB

### ISSUE THREAD

**Issue by nyankoframe** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#152]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Stray

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz

### GPU Driver Version [Required]

- [ ] 30.0.101.3113 (*latest*)
- [ ] 30.0.101.3109
- [X] 30.0.101.1994
- [ ] 30.0.101.1960
- [ ] 30.0.101.1934
- [X] 30.0.101.1660
- [ ] 30.0.101.1631
- [ ] 30.0.101.1404
- [ ] 30.0.101.1340
- [ ] 30.0.101.1191
- [ ] 30.0.101.1121
- [ ] 30.0.101.1069
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [x] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [X] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

Anonymized SSU attached
[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9146322/igcit_ssu.txt)

### Description and steps to reproduce [Required]

1. Launch Stray from Steam or from Start menu
2. Error message observed immediately

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

n/a - game does not launch

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

n/a

### Device / Platform name

Intel NUC NUC6i5SYB

### Crash dumps [Required]

n/a - application error, not a crash

![stray_crash_on_skl_nuc](https://user-images.githubusercontent.com/69328423/179892078-83bea39e-21b9-4862-9e9c-e082c1be0f68.jpg)

**Comment by nyankoframe** [comment]
There is a different error message when launching Stray in DX12 mode.
![Stray_dx12_crash](https://user-images.githubusercontent.com/69328423/179893504-237e768d-57d6-4c07-8bbb-e07dd90b0862.jpg)

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe, 
To narrow down the issue could you confirm whether you did the below steps. If not please give it a try and let us know your updates:
1. Verify the integrity of the game files:

        • Open Steam, and navigate to your library
	• Right-click on Stray in your library, and click Properties
	• Now, in the LOCAL FILES tab, select Verify Integrity of local files…
	
2. Clean installation of Intel Graphics Driver:-
	Follow the steps below to completely uninstall and reinstall the graphics driver:
	 
       1. Open the Device Manager using the steps provided for your operating system:
			○ Windows 11*/10*/8.1*: Right-click the Windows Start button. Select Device Manager.
			○ Windows 7*: Click Windows Start, click Run, type: "devmgmt.msc"
		2. Expand the Display adapters section.
		3. Identify the Intel Graphics device among the options listed.
		4. Access [Download Center](https://www.intel.com/content/www/us/en/search.html?ws=text#t=Downloads&layout=table&cf:Downloads=[%7B%22actualLabel%22%3A%22Graphics%22%2C%22displayLabel%22%3A%22Graphics%22%7D]), search for the Intel Graphics model identified in step 3 using the Search box located in the top-right corner.
		5. Select the driver from the list that is designated for the operating system (Windows 11/10, 8.1, or 7).
		6. Download the .exe file.
		7. Disconnect from the internet to make sure the driver will not be automatically updated by Windows.
		8. Go back to the Intel Graphics entry in the Device Manager.
		9. Right-click on Intel Graphics and click Uninstall."
		10. In the device removal dialog box, check Delete the driver software for this device and click OK.
		11. Restart the computer after the uninstallation is complete.
		12. Open the Device Manager.
		13. Expand the Display adapters section again.
		14. If no older drivers are stored in the system, the graphics controller in device manager should now be listed as 
		Microsoft Basic Display Adapter, Standard VGA Graphics Adapter or similar. If not, repeat steps 8 through 11.
		16. Reboot the computer when prompted.
		
	3. Ensure that you are on the latest version of Windows?
	4. Did you verify the issue on any other device other NUC? Please confirm whether the issue is specific to your device?
	5. Did you try with the latest dxvk verson ?If not, just give a try the below:
Download dxvk from the link  [dxvk release ](onenote:#Issue&section-id={7B2DD7B6-D7FE-4DA9-95BA-31039C933001}&page-id={7E7389E2-DE92-496F-8CE4-273985C1C71C}&end&base-path=https://intel-my.sharepoint.com/personal/arunx_rajan_intel_com/Documents/Documents/OneNote%20Notebooks/My%20Notebook/Game%20Developers.one), extract the files, copy dxgi.dll to Stray's installation directory and run Stray. Right-click Stray in your Steam library > Manage > browse local files. A new window will open with the game files. Paste the dxgi.dll file in the Win64 folder.

If you confirm the above steps and still encounter the same issue, we will proceed to the next step.

**Comment by nyankoframe** [comment]
> 1. Verify the integrity of the game files:
>    • Open Steam, and navigate to your library
>    • Right-click on Stray in your library, and click Properties
>    • Now, in the LOCAL FILES tab, select Verify Integrity of local files…

This does not resolve the issue.

> 2. Clean installation of Intel Graphics Driver:-
>    Follow the steps below to completely uninstall and reinstall the graphics driver:

I am currently running DDU to remove all graphics drivers and will then reinstall 1994 driver.

> 3. Ensure that you are on the latest version of Windows?

I am on the latest version of Windows 10. This NUC does not meet the Windows 11 system requirements.

> 4. Did you verify the issue on any other device other NUC? Please confirm whether the issue is specific to your device?

I am able to launch Stray on LG Gram laptop (Intel i7-1195G7 CPU).

> 5. Did you try with the latest dxvk verson ?If not, just give a try the below:
>    Download dxvk from the link  [dxvk release](https://github.com/doitsujin/dxvk/releases), extract the files, copy dxgi.dll to Stray's installation directory and run Stray. Right-click Stray in your Steam library > Manage > browse local files. A new window will open with the game files. Paste the dxgi.dll file in the Win64 folder.
 
Will try this after step 2.

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe, 
Thank you for the quick check and update. Since you are still observing the issue could you try the below steps too:
1. Disable Steam Overlay on the Steam App.
     Right Click on the game -->Select Properties -->Uncheck the option “Enable the Steam Overlay while in game”-->Launch the Game
If you are still observing the issue please try the below steps 2 and 3
2. Perform Clean boot by following the link [Clean boot](https://support.microsoft.com/en-us/topic/how-to-perform-a-clean-boot-in-windows-da2f9573-6eec-00ad-2f8a-a97a1807f3dd)
3. Uninstall and reinstall the game to the “different drive”. Please ensure the game folder and files are removed from the system before reinstalling the game.

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe , In case the above recommendations do not work for you, try setting the steam launch option to "-dx12" and see if it helps.
**Steps to follow:**
1. Open your Steam Library
2. Right-click the game's title and select Properties.
3. On the General tab you'll find the Launch Options section.
4. Enter the launch options as "dx-12"
5. Close the game's Properties window and launch the game.

**Comment by IntelSupport-Rozilah** [comment]
Hi @nyankoframe
just for follow-up, do you try the steps provided by @IntelSupport-Arun  for our next steps?

**Comment by nyankoframe** [comment]
Hi,

- Stray still crashes with disabling Steam overlay
- I do not have a different drive to try installing on
- Stray still crashes with DX12 option

I have attached the screen shots of the crash earlier in this issue.

**Comment by Hyatice** [comment]
Hey @nyankoframe - not from Intel here. By any chance does this happen pretty much on launch of the game? Say... black screen for 5 seconds, and then crash/error?

If so... This may be the "TDR" issue where intel takes just a little too long to load some textures or something else, and windows assumes it's frozen and forces it to close.

The fix is to add the following two registry entries:

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
"TdrDelay"=dword:0000003c
"TdrDdiDelay"=dword:0000003c

If this is something you've already tried, ignore me, but figured I'd toss my two cents in.

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe ,

Thank you for the update and comment.
One quick check from your side, did you try to launch the game from the local folder? if you have already launched the game from your local folder as administrator what was the observation? 
Also, could you double confirm the [visual C++](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/visual%20C++) is updated?If not please update and check.
Also, can I request the video of your issue reproduction steps?
In between, I have tested the issue on our systems, and the issue is not reproducible. Details are below :
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/rajanax/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/rajanax/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/rajanax/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Test | 1 | 2
-- | -- | --
Issue Reproduced(Yes/No) | No | No
CPU Generation | RocketLake | AlderLake
Operating System & Version | Windows   10 21H2 | Windows   10 21H2
Graphics Driver Version | 30.0.101.1994 | 30.0.101.1994
Display Interface Used | DP | DP
Game Platform | Steam | Steam
Observation | Able to launch the game without any issue | Able to launch the game without any issue




</body>

</html>

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe ,
Is there any progress after updating the [visual C++](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/visual%20C++) and running the game as administrator from the local?

**Comment by nyankoframe** [comment]
Hi, I won't be able to try out the recommendations until next week.
________________________________

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe , Since the new graphics driver 31.0.101.2111(https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html)has the fix the for the game crash issue you may try with the same. We hope your issue will fix with this latest driver release.

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe ,
Have you had a chance to test out the latest graphics driver provided?

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe ,
Did you get a chance to test the issue with the latest graphics driver?
Try the latest graphics driver provided before trying the other recommendation if you have not yet verified the issue. This driver version 31.0.101.2111 has the latest fix for the launching issue, so your issue should be resolved.
Please give a try and let me know the result.

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe ,

Have you had any chance to verify the new driver?

**Comment by IntelSupport-Arun** [comment]
Hi @nyankoframe ,
Were you able to test the new driver? any update for us?

**Comment by nyankoframe** [comment]
With 31.0.101.2111 and Stray Update 3, I was able to launch the game. The game patch notes have the following update:

> Additional fixes for GPU crash on boot issues
> Engine fix for some users who are unable to boot due to GPU driver issues

I think this issue can now be closed.

**Comment by IntelSupport-Arun** [comment]
Hi @IGCIT,
Since the issue has been resolved please proceed to close the case.
