### ISSUE TITLE
Borderlands 3 instantly crashing upon launch A770 16GB LE

### ISSUE THREAD

**Issue by Pure-Fox** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#174]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Borderlands 3

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

13900k

### Graphic Card [Required]

Intel Arc A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3793 (*latest*)
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9943005/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Prior to win11 upgrade, there was no issue launching borderlands 3 on A770. After the upgrade to windows 11 22H2, I am no longer able to launch the game while using A770. I have tried DDU the driver and reinstalling, with no effect.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3440x1440

### Game VSync [Required]

Off

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Game cannot be launched.

### Crash dumps [Required, if applicable]

[unreal-v2860060-2022.11.04-23.03.59.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9943008/unreal-v2860060-2022.11.04-23.03.59.zip)
[UE4CC-Windows-FC8259444FCE74334DD98AB8118989BB_0000.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9943009/UE4CC-Windows-FC8259444FCE74334DD98AB8118989BB_0000.zip)

### Game custom logs
[unreal-v2860060-2022.11.04-23.03.59.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9943010/unreal-v2860060-2022.11.04-23.03.59.zip)
![Borderlands3_1088COKOzN](https://user-images.githubusercontent.com/52764769/200100412-1b86194a-c010-4741-b9b9-77c88aebd632.png)

**Comment by Pure-Fox** [comment]
Coincidentally, using DX11 also results in game crashing, but without a crash log. It would load the various logo at launch, then crash.

**Comment by IntelSupport-Arun** [comment]
Hi @Pure-Fox ,

For further investigation we would like to know below information :
1. Could you double confirm the OS build version using is Windows 11 Pro 64-bit (10.0, Build 22621)?
2. Please confirm the previous working Windows Version?
3. Did you get any chance to verify the issue with the previous driver [31.0.101.3490](https://www.intel.com/content/www/us/en/download/726609/intel-arc-graphics-windows-dch-driver.html)? If yes, please let me know the observations?
4. Is the issue is specific to ARC LE 770 or did you able to verify the issue with any other brand?

**Comment by Pure-Fox** [comment]
Hello! I can confirm the version of the OS is Edition	Windows 11 Pro 22H2 22621.674. Unfortunately I no longer have the previous system, I think it is probably an up to date 21H2?
I haven't got the chance to test the previous stable version, thinking it might lack certain bugfixes. I might test it when I have the time later on. The issue is specific to A770 because the integrated graphics or the other nvidia gpu worked without issue.

**Comment by IntelSupport-Arun** [comment]
Hi @Pure-Fox ,
Thank you for the details.
We are verifying the issue on our side. Please stay tuned. Thanks.

**Comment by IntelSupport-Arun** [comment]
Hi @Pure-Fox ,

I have verified the issue in our lab on multiple platforms and am able to launch the game without any crashes. Here is our test result and details :
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



Test | 1 | 2
-- | -- | --
Issue Reproduced(Yes/No) | No | No
CPU Generation | 11700 | AMD Ryzen 7 5800x
Discrete GPU | BARC 700 LE 16Gb | BARC 700 LE 16Gb
Operating System & Version | Windows   11 22H2 | Windows   11 22H2
Graphics Driver Version | 31.0.101.3490/31.0.101.3793 | 31.0.101.3490/31.0.101.3793
Display Interface Used | DP | DP
Game Platform | Steam | Steam
Game Graphics Quality | Low | Low
Game Resolution | 3840x2160 | 3840x2160
Game Vsync (ON/OFF) | Off | off
Window Display Configuration | Windowed Borderless | Windowed Borderless



</div>


</body>

</html>


https://user-images.githubusercontent.com/91881865/202105752-4ffc16ca-eb2a-4808-9b6c-6d22625f8e18.mp4

But in your issue description, you mentioned that you set the resolution to 3440x1440 in Borderless Windowed mode. However, I can only set (default) 3840x2160 when connecting 4K display(BenQ EL2870U) display.
![image](https://user-images.githubusercontent.com/91881865/202092447-9cffbd54-d3a7-4573-bc09-3bd9cd6f918c.png)

From our observations, I suspect the issue is specific to your system. Could you give a fresh installation of the OS, game, and Graphics driver from your side and let me know your observations? Also, please verify the issue with a different display as well.

**Comment by IntelSupport-Arun** [comment]
Hi @Pure-Fox ,
May I know the update from your side? Also, a new driver has been released [31.0.101.3802](https://www.intel.com/content/www/us/en/download/729157/intel-arc-graphics-windows-dch-driver-beta.html?wapkw=arc) and you may please verify the issue with this too.

**Comment by IntelSupport-Arun** [comment]
Hi @IGCIT , Please close this case since we are unable to reproduce the issue with the latest drivers and we have not heard back from the customer for so long.

**Comment by Pure-Fox** [comment]
Hi, Sorry github update got sent to spam and I wasn't able to see any updates. I will try the new driver when I next get the chance, but if you can't replicate the error then it might be something with my system. I'll just close the issue for now :)
