### ISSUE TITLE
Desktop Background does not display after installing 3975 driver

### ISSUE THREAD

**Issue by bizude** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#194]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Windows 11

### Processor / Processor Number [Required]

Intel i9-13900K

### Graphic Card [Required]

Intel ARC A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.3975 (*latest*)
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Windows 10 21H1
- [ ] Other (Please specify)

### Intel System Support Utility report

[asd.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10253180/asd.txt)

### Description and steps to reproduce [Required]

Upgrade to 3975 from 3959, reboot computer. Upon rebooting the desktop background did not display. It did not display again after rebooting once more. It was fixed by telling Windows to go to the next wallpaper. 
![image](https://user-images.githubusercontent.com/81831122/208281353-dfea8281-2b0c-46f1-9cd2-7ebab2bdf56b.png)

**Comment by IntelSupport-Rozilah** [comment]
hi @bizude,
Thanks for contacting Intel, after you upgraded to 3975 and there is no display as you mention, do you try disconnect the current display cable(e.g: HDMI) from A770, then connect DP cable to any of the display port on A770?,

**Comment by IntelSupport-Rozilah** [comment]
hi @bizude,

i have done verify this issue,  i tested on three different systems and the issue is not reproducible to all systems as below result:
![image](https://user-images.githubusercontent.com/44628772/208592628-4d978bcf-d74e-47d8-a92a-7fd1b2f2a3fa.png)

The screenshots of the desktop background before and after upgrade driver on all system as below:
1. ADL
- on 31.0.101.3959
![adl_3959_desktop background](https://user-images.githubusercontent.com/44628772/208592983-1c186ea1-db56-4448-81ce-d6683511f0cd.png)
- on 31.0.101.3975 
![adl_3975_desktop background](https://user-images.githubusercontent.com/44628772/208593204-b1b0a986-c2fe-4584-b3fd-38ac7870407d.png)

2. RLK
- on 31.0.101.3959
![rlk_3959_desktop background](https://user-images.githubusercontent.com/44628772/208593298-fbde1a56-e63d-437f-ab91-3f4f4d3821ca.png)
- on 31.0.101.3975 
![rlk_3975_desktop background](https://user-images.githubusercontent.com/44628772/208593337-16ef97a6-93c7-44a4-8211-cac76098e7a4.png)

3. AMD
- on 31.0.101.3959
![AMD_3959_desktop background](https://user-images.githubusercontent.com/44628772/208593398-3bf887a1-67fb-491d-91f7-392295aae6d8.png)
- on 31.0.101.3975
![AMD_3975_desktop background](https://user-images.githubusercontent.com/44628772/208593446-0590f91d-f62b-401f-bb03-b9619b14a208.png)

what i can suggest to you is try Execute a Clean Installation During Driver Installation from here https://www.intel.com/content/www/us/en/support/articles/000057389/graphics.html, hope can help to solve your issue.

**Comment by IntelSupport-Rozilah** [comment]
hi @bizude, 
do you have any updates?

**Comment by IntelSupport-Arun** [comment]
Hi @bizude ,
Since we are not able to reproduce the issue with multiple drivers on different platforms we would like to close this case. Before closing the case may I know did you try the clean installation of the driver?

**Comment by bizude** [comment]
Hi, all I can say is that this happened after a normal upgrade of the driver and it was fixed by changing the wallpaper to the next one.
