### ISSUE TITLE
Installer BSODs when using both Discrete A770LE and UHD 770

### ISSUE THREAD

**Issue by tazerwhip** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#216]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel ARC Driver Installer

### Processor / Processor Number [Required]

i7-12700k

### Graphic Card [Required]

A770LE & UHD 770

### GPU Driver Version [Required]

- [X] 31.0.101.4034 (*latest*)
- [X] 31.0.101.4032
- [X] 31.0.101.3975
- [X] 31.0.101.3959
- [X] 31.0.101.3802
- [X] 31.0.101.3793
- [X] 31.0.101.3491
- [X] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [x] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [X] Windows 11 21H2
- [X] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[IntelSSUReport.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10415963/IntelSSUReport.txt)

### Description and steps to reproduce [Required]

Run installer from either the zip package or self-installing .exe, while using both the iGPU and discrete Intel GPU (A770LE). When attempting to finish installing the driver for the discrete GPU a BSOD will happen. Has happened with all driver versions I have used since installing GPU in September. 
Most recent driver package (*.4304 Jan 10, 2023) changed the BSOD from Video_Scheduler_Internal_Error (0x119) to Kmode_Exception_Not_Handled (0x1e). Driver seems to be installed fine upon reboot, both GPUs have the proper version showing in Device Manager. However I feel that the BSOD fails to allow the other software components to install/update. The BSOD will happen regardless of Clean Install or not. Because I know how to use add/remove programs, whatever DDU does to a system hasn't happened.

### Device / Platform

TUF GAMING Z690-PLUS WIFI D4

### Crash dumps [Required, if applicable]

[igcit-dumps_72a0c60d.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10416055/igcit-dumps_72a0c60d.zip)
Extracted from IGCIT encrypted .7z then repackaged as unencrypted .zip due to extension conflict.

### Application / Windows logs

[bugcheck0x1e.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10416073/bugcheck0x1e.zip)
Bugcheck .evtx from EventViewer.

**Comment by tazerwhip** [comment]
Slightly minor issue, as it's more of a 'niche' scenario where I am using both iGPU and A770 due to refresh differences on 2 monitors. Graphic issues happened due to use of 165hz and 60hz monitors on A770; rather than mess with differing manual refresh rates, used the iGPU for the 60hz monitor.

**Comment by tazerwhip** [comment]
Uploaded to YouTube due to size attachment size limitations: https://www.youtube.com/watch?v=GMEcMjy-crs

As I mention during the video, the clean install issue has been solved. I forgot to do my due diligence, and when the repair install failed, assumed that the clean install method was still experiencing the same issue. Went back to *.3959 via clean install with the installer, and it didn't BSOD. Now the BSOD will only appear when performing an upgrade install. 

To explain the 'silly' setup; when I would run the DP, 165hz monitor & HDMI 60hz monitor on the A770 I would have tearing/stuttering/blank-outs (somehow the YT window would stop rendering all frames - think loading any current YT on 56kbps dial-up) happen when doing something as simple as scrolling reddit (on the 60hz) while playing a YT video (on 165hz). 
Rather than find a happy medium of differing refresh rates, I decided to just run the 60hz HDMI monitor from the iGPU; that fixed the video tearing issue. So the DP 165hz monitor is the only thing on the A770, and HDMI 60hz only on UHD 770.

**Comment by IntelSupport-Rozilah** [comment]
@tazerwhip, thanks so much for the video. It's very clear for us to start verifying the issue, we will try replicate the issue as close as your setup and will update you soon.

**Comment by IntelSupport-Rozilah** [comment]
hi @tazerwhip,
we have verified the issue is not reproducible on our system as below:
1. Tested on different driver version upgrades, the installation is successful without any BSOD happening.
![image](https://user-images.githubusercontent.com/44628772/213644758-3f8103d0-e9d3-43c0-904f-ddc494da2445.png)
I also attached a video during installation here: https://www.youtube.com/watch?v=DcsU6DQQG70 as your reference for Test number 2.
2. Tested on different driver version upgrades, another monitor and OS. The installation is successful without any BSOD happening.
![image](https://user-images.githubusercontent.com/44628772/213646509-dd71ee5b-ac10-4300-ab26-cafea305f483.png)

can you try any of the steps provided below:
1. try changing to another type of monitor?
2. do the window update and make sure you in lates bios.

**Comment by tazerwhip** [comment]
Thank you for the test/results. I imagine this is unique to my exact BOM at this point. Unfortunately, I do not have access to other monitors with the same config. I haven't seen a recent BIOS update to apply either.
There's another issue I hadn't reported yet, but I'm thinking it might have something to do with this one now. Would it be possible for the Realtek integrated audio controller to cause the BSODs? 
I mention the audio controller as the separate issue that showed on the system after ARC was installed is related. When there's data/network activity (sometimes even scrolling reddit) audio can provide a tearing / distortion sound. I'm thinking that there's something wrong with it. However, it was not present in the previous setup using GTX970.
Feel free to close this thread, if I can gather decent 'evidence' will start a new thread for the audio issue.

**Comment by IntelSupport-Rozilah** [comment]
hi @tazerwhip, 
Sorry for the late reply because currently we have a high volume of issues and will try to help you as we can.
1. if you have a chance to access the monitor maybe you can try to connect both monitors on two of the Arc ports, disable iGPU in BIOS and reinstall the driver, then check if BSOD happens or not.
2.  Would it be possible for the Realtek integrated audio controller to cause the BSODs? --> can you disable this controller first before installing Arc driver, then proceed with installing the diver and check BSOD will occur or not.
3. It would be better if you can capture the dump file or  Event viewer to find the root cause.
4. please feel free to report another new issue on the audio issue once you have enough info for it.

**Comment by IntelSupport-Rozilah** [comment]
hi @tazerwhip,
Please to inform that we are proceeding to close this case since there is no response from your side. If you require any further assistance please follow our suggestions and update your finding, then we will resume our support again. You may submit a new GitHub case if you have new questions and we are happy to assist you.

**Comment by IntelSupport-Rozilah** [comment]
hi @IGCIT,
can you please close this issue since there is no response?
