### ISSUE TITLE
Oculus rift support 

### ISSUE THREAD

**Issue by gunkiller506** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#220]
### Application [Required]

Oculus app

### Processor / Processor Number [Required]

12400k

### Graphic Card [Required]

Arc a750 Challenger oc edition 

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H1
- [X] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

The Oculus rift isn't seen with the app so it won't connect

**Comment by IntelSupport-Rozilah** [comment]
hi @gunkiller506,
Thanks for contacting Intel,
can you provide the below details of the issue:
1. What driver version?
2. Step to reproduce the issue?
3. Video or screenshot of the issue?
4. Attach SSU log of the system.

**Comment by IntelSupport-Rozilah** [comment]
hi @gunkiller506,
I got confirmation from the Internal team, this issue is similar to [184](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/184). As for now we have to close this issue first as we mentioned before "Intel Arc graphics support for VR headsets continues to evolve as we ramp our products and add updates to our software stack. At this time we are unable to provide a target date for when each VR headset will be enabled"
