### ISSUE TITLE
Partial implementation of ResizeBAR in Arc?

### ISSUE THREAD

**Issue by LancerDawg75** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#330]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Cap FrameX + GPU-Z

### Processor / Processor Number [Required]

AMD Ryzen 7 5800X3D

### Graphic Card [Required]

Intel Arc A770 Limited Edition

### GPU Driver Version [Required]

- [X] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [X] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

Not really sure if applicable here. It's just an observation.

### Description and steps to reproduce [Required]

When I was doing CFX runs with Like a Dragon, I noticed in the lower portion of CF-X that ReBar is only partially implemented in Arc. I am not really sure if this a huge issue, but it is something that I noticed.

- HW ReBAR is enabled
- DX ReBAR is enabled
- Vulkan ReBAR is disabled

Reinforcing this point, when I look at GPU-Z in Advanced for Vulkan information, it does match up that ReBAR for Vulkan is not present as the Host-Device, Device-Local memory pool is limited to 256MB. If I understand correctly when ReBAR is enable for Vulkan, all memory should be at the same size as the VRAM.

I'm posting this because I am wondering if this is somehow related to the issue that we are seeing with Arc Control stating that ReBAR is "Not Supported" because all three aspects are not enabled?

![CFX-ResizeBAR](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/9c436c37-7811-46fd-aac3-fcfbcf3d4c27)

![Vulkan ReBAR](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/2ae3c6f2-10cc-4b1c-b041-74417559633a)

**Comment by LancerDawg75** [comment]
It might be a platform issue seeing that you're on an Intel platform and I'm on AMD. 
I just upgraded to the latest beta driver to see if that was the issue because I see that you're on 4389 and when I took that snapshot, it was the latest WHQL. 

Using CapFrame X 1.7.1 portable. Yeah, it still shows a 256MB Device-Local/Host-Visible allocation. 
GPU-Z 2.53 reinforces that in the Advanced > Vulkan info tab
PCIE ReBAR tab shows that everything is enabled and supported

Possible relevant addendum - I did recently update the chipset drivers from the AMD support site to the most recent version, but I can't say if that was the issue, but looking at the release notes for the most recent version, [not a whole lot was changed.](https://www.amd.com/en/support/kb/release-notes/rn-ryzen-chipset-5-05-16-529)

**Comment by Arturo-Intel** [comment]
Ok, if I disable my iGPU I can see that the Vulcan ReBar is disabled. 
It confirms the dependency of the usage of a Intel Platform as you mention above

**Comment by LancerDawg75** [comment]
That's....interesting. 
Not good, but interesting.

Question:
Can you check GPU-Z while your GPU is enabled and then look at each GPU? It makes me wonder if it's iGPU that is taking on the DL/HV BAR by itself, or it's supplanting the Arc in a sort of heterogenous nature.

Also, I wonder if when you disable the iGPU, does Arc Control show "not supported" for you.

On my side, I'm going to try one more thing, because I remember that Arc Control would state that ReBAR was on and functioning when SVM/Virtualization was turned off, and see if that also affects the Vulkan ReBAR pool towards a positive result.

Because right now, it looks like 

- If Intel platform users bought KF processors, then ReBAR is only a partial implementation and you're out of luck. 
- AMD platform users are just simply out of luck no matter what

**Comment by AuspiciousAlmonds** [comment]
Here's the data from my system. Ryzen 7950x, ARC A750, went ahead and disabled SVM. Performance pretty bad 1920x1080 - 3840x2160 all settings at the lowest besides render scale being 100%. Just tried 1920x1080, everything set to low/off with render scale at 100% getting 30-50fps in the areas with a crowd. Arc Control said resizable bar was enabled with SVM on and off

<img width="631" alt="Screenshot 2023-06-02 082451" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/8890245/a5d34180-1859-4fe4-b97e-2512b4f0e864">

**Comment by Arturo-Intel** [comment]
OK, l think we have a solid case here, let me share this data to the corresponding teams and I will be back when I have news on it.

Thank you all for your time, 
--r2

**Comment by Karen-Intel** [comment]
Hey guys just a quick update. Like Arturo mentioned we have confirm this behavior is not expected.
We are reporting it asap and will make sure to share with you when we have a fix available in a public release.
Let's keep this post open until we have news so, stay tuned and thanks for all your help!

Karen

**Comment by Rotluchs** [comment]
I recently benchmarked Baldurs Gate 3 on my Arc A770 + Ryzen 5600 (has no iGPU) on an Gigabyte X570S UD
(performance is sub-par btw and the Arc is falling far behind the RX 6700 XT / RTX 3060 Ti , way more imho then it usually does these days) ..

first I tried on DX11 , and thought okay, maybe that's why - but on Vulkan (which has better min fps / percentile lows / frametimes, but so does every other card, and on Vulkan the A770 was still way slower than usual compared to comparable AMD/Nvidia competitors)
Could be, bad intel arc drivers (I tried Baldurs Gate 3 'game ready' driver * version.4578 , which has literally next to zero improvements compared to previous *.4577 driver)
Could be, Larian's Divinity Engine just isn't well optimized for Arc in particular or cards that have lots of vram in general on their end (it doesn't use much imho, not even on 4k ultra)

anyway, I was using capframeX (which I hadn't been using for quite a while) and I certainly never noticed the rBAR indicator it has, at least I never bothered. but I did saw it the other day,

which is why I googled it (and because Arc performed so 'bad' in BG3) and so I somehow found this info here on github..

here's my system ( though I guess I you don't need any more confirmation)

Ryzen 5600 (no iGPU)
Arc A770 16GB LE
2x16 GB DDR4 Ram
Windows 10 (up to date as of writing)

No idea if everything is working as it should, aside from what the different tooltips / info tabs say,
(because maybe it's just a specific GPU-Z / capframeX 'display' issue getting the right info/data and how they query stuff, I don't know)

meaning for Vulkan on Windows in particular,
if performance could/should be higher as it currently is (with rBAR enabled in BIOS),

but I can definitely notice a major difference when I disable rBAR in Bios

(my  gigabyte x570s UD am4 board only has the option 'auto' or 'disabled' for rBAR)  : 
![Arc Windows reBAR Vulkan Off](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/141880753/93f3d1ea-50cb-4398-b823-ab6bc1134e4b)
![gpu-z rebar tab](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/141880753/2e12f0c7-252d-4335-9a6c-17bee39f701b)
![gpu-z vulkan advanced tab](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/141880753/2f5ebac5-641e-43df-b6aa-b3074c698988)

I'm also writing in here, because I see something that appears to be an additional HAGS indicator in your screenshot, @AuspiciousAlmonds ? it's cut off, so not 100% sure.

Find it interesting, because I dont have that indicator here, at all.. what does it say?
Is capframex perhaps reporting your AMD CPU iGPU values here ?
in gpu-z, what have you selected on bottom left drop down menu in the screenshot of the vulkan advanced tab ?

As far as capframex goes, Im running version 1.7.2 beta (rev 13)

Still haven't found any screenshots of GPU-Z advanced tab for those Vulkan Infos & the Memory section it has there,
for current/last gen AMD Radeon / Nvidia Geforce  GPUs for cross reference.. what does it look like, there ?

**Comment by Arturo-Intel** [comment]
Quick update:
Seems that this issue with resizeBar in CapFrameX is a bug on the capframex side, our devs notice that the sw is not detecting correctly the enablement of the resizeBar (with out the igpu) 

I will keep you informed in this thread the progress on this.

-- r2

**Comment by LancerDawg75** [comment]
> Quick update: Seems that this issue with resizeBar in CapFrameX is a bug on the capframex side, our devs notice that the sw is not detecting correctly the enablement of the resizeBar (with out the igpu)
> 
> I will keep you informed in this thread the progress on this.
> 
> -- r2

But this also begs the question of:

> Are we saying that GPU-Z is also reporting ResizeBAR incorrectly through their software like CFX?

Because if I look at the information between the two applications, CFX is corresponding to the same reporting from Memory 4 of GPU-Z (256MB chunks vs 16254MB should ReBar be implemented properly as demonstrated by your CFX information status when you had your iGPU enabled.) The only thing that I didn't see is if your GPU-Z corroborates the same information on Memory 4 when you do and don't have your iGPU enabled. 

If that's the case, then the engineers need to get with W1zzard at TechPowerUp! to explain how their implementation of ResizeBAR works on the Xe architecture to properly display it.

**Comment by nyanmisaka** [comment]
@Arturo-Intel You can use the [official tool](https://vulkan.gpuinfo.org/downloads/vulkancapsviewer_3.31_win64.zip) from [Khronos Group](https://vulkan.gpuinfo.org/download.php) to check this. It shows the exact same 256MB Rebar size.

268435456Byte / 1024 / 1024 = 256MB in (DEVICE_LOCAL_BIT | HOST_VISIBLE_BIT | HOST_CONHERENT_BIT)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/14953024/fc404c1d-72a9-40df-8166-34df75cb97e7)

**Comment by Rotluchs** [comment]
regarding Intel, the communicated importance of having reBAR supported/enabled , Vulkan drivers, 

and from what's visible in Khronos own Vulkan HW caps viewer,

this really isnt what I thought it will look like on Arc & it's  Vulkan drivers, especially after reading this:

https://www.asawicki.info/news_1740_vulkan_memory_types_on_pc_and_how_to_use_them

given from what it looked like, back then and now, on AMD & Nvidia  gpu's,

I was now really expecting to see at least one heap visible here on Arc as well
that exposes entire VRAM via device_local & host_visible bit - but it's not there. 

but what does it even mean, so far?
what are the downsides/benefits of (not) having it?
on windows & vulkan, are Arc dGPUs less stable or slower now than they should be?

**Comment by Leopard1907** [comment]
@Rotluchs Historically Intel never bothered that much Khronos api's support on Windows.

So that should not be surprising, actually i wouldn't be surprised if Intel drops Vulkan all together when MS pushes a Vulkan on D3D12 layer ( it is in WSL for now ) on Windows.

Remember, they also jumped on 9on12 at Arc launch.

**Comment by Karen-Intel** [comment]
Hi guys, can you help verify with driver v.101.5518?

On my end it shows as Resizable bar: On with both Integrated and Discrete GFX cards enabled

We just need your confirmation to mark this issue as fixed. 

Hope to hear from you soon

Karen

**Comment by Rotluchs** [comment]
![5445 no vulkan rebar reBar](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/141880753/4eea59c9-be11-40d4-8c91-9db828f5a955)
top: before
bottom pic: after (express install, no clean DDU/Clean install this time)
though, I havent checked  what's reported inside Vulkan Caps Viewer yet..:
![5518 vulkan reBar support reported as ON](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/141880753/11fcf040-3925-4e2b-b5c1-67de81c39241)

**Comment by LancerDawg75** [comment]
Signing in! 

Just installed 5518

GPU-Z
![vulkan-rebar](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/64382174-b7e6-4664-b05a-d5e03910ac2a)

and CapFrameX
![capframe resizebar](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/55825789/5d463c07-70ad-4479-a5c7-23702a13abb1)


So yay! ^_^

**Comment by akarnokd** [comment]
A770LE Confirming it worked
![5445](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/51c36651-46c7-4748-a7b0-acd6dce385f7)
![5518](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/1269832/d1e70632-41c0-422b-84d9-75d9847b26ad)

**Comment by Karen-Intel** [comment]
Thank you everyone for confirming so quickly!

If you have any additional feedback please share. It will help us improve and, as always, we're here to help!

Karen
