### ISSUE TITLE
Instant replay recordings

### ISSUE THREAD

**Issue by zrmdsxa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#378]
### Application [Required]

Intel Arc Control

### Processor / Processor Number [Required]

NA

### Graphic Card [Required]

NA

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

I request for intel arc control to have the ability to save recordings using an instant replay buffer with a max length of at least 20 minutes, and bitrate of 25 mbps. The program should be able to detect and hook into games automatically.

### Additional notes

If you want to rival NVIDIA's geforce experience and AMD's ReLive then you must be able to do this

**Comment by Karen-Intel** [comment]
Hey @zrmdsxa that is a great suggestion!

Adding it to our feature request list, all this suggestions help make our products better :)

Have a great day

Karen

**Comment by GottaSlay** [comment]
This is a feature i miss from AMD Adrenalin software. Hopefully Intel will have a similar feature soon!

**Comment by Gabriela-Intel** [comment]
Thanks all for the feedback! :)

@IGCIT Please close

**Comment by BuyMyMojo** [comment]
Does the issue being closed mean this feature is being worked on?

**Comment by Gabriela-Intel** [comment]
Not exactly. We're closing out feature requests because we can't guarantee that the teams will be able to take on the task or agree to implement the feature due to a variety of reasons (managing priorities, workload, other issues & feature requests, etc.). That doesn't mean that it isn't a great idea though. :)

Not only that but it's most common that it takes quite a while (I'm talking about at least 6+ months) for the team to make the changes, implement it, and test it once they decide to move forward with the feature.

I will say that we currently are tracking this internally and making sure to the right team. We'll try our best to push to get the feature implemented 👍
