### ISSUE TITLE
Devil May Cry 4 Special Edition Crashes Directly

### ISSUE THREAD

**Issue by Eschryn** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#387]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Devil May Cry 4 Special Edition

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 9 5950X 16-Core Processor

### Graphic Card [Required]

Intel(R) Arc(TM) A750 Graphics

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [X] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

# SSU Scan Information
Scan Info:
 Version:"2.5.0.34"
 Date:"07.15.2023"
 Time:"00:00:28.7687307"

# Scanned Hardware
[info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12061969/info.txt)

### Description and steps to reproduce [Required]

When starting the game, create a new save game, if you can, and at some point it'll crash.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

default settings

**Comment by LancerDawg75** [comment]
Might try [DXVK Async](https://github.com/Sporif/dxvk-async) to see if it will work that way as with the way Arc is, a good portion of games that predate DX12 or Vulkan have wildly mixed results. 

It's a bit of work, but once you get used to it, it's pretty easy to do. 

- You will need to get the [tar.gz file here](https://github.com/Sporif/dxvk-async/releases/tag/2.0) and you'll need [7-zip](https://www.7-zip.org/download.html) to unpack it
- Once you do unpack it far enough, you'll see two folders x32 and x64, these are the ones you want to extract
- For this game, you'll need to get the files from the x64 folder
- You will need to copy two files (not the entire x64 folder. If you do that, it won't work)
  - dxgi.dll
  - d3d10core.dll
 - Paste those two files in the same folder that the game's exe file is at

Since this is the Async version, you must do a little bit more in the system's environment variables to have it perform (potentially) better.

> Set the environment variable DXVK_ASYNC=1

Easiest (or really semi-faster way) of doing it is:

- Type in Windows search "environment" -- you should see "Edit the system environment variables"
- You will be taken to "System Properties"
- Click on the Environment Variables radio button
- Press the "New" button on the bottom box labeled "System Variables"
  - In "variable name" type in DXVK_ASYNC
  - In "variable value" type in 1
  
  You might also want to keep those two folders of DXVK Async handy because there is a pretty good chance you'll be copying those two dll files rather often if some particular game that is DX9/10/11 and it doesn't perform the way it should.

**Comment by Karen-Intel** [comment]
Thank you for your help @LancerDawg75 :)

@eschryn Have you been able to test the WA?

Karen

**Comment by Eschryn** [comment]
> Might try [DXVK Async](https://github.com/Sporif/dxvk-async) to see if it will work that way as with the way Arc is, a good portion of games that predate DX12 or Vulkan have wildly mixed results.
> 
> It's a bit of work, but once you get used to it, it's pretty easy to do.
> 
> * You will need to get the [tar.gz file here](https://github.com/Sporif/dxvk-async/releases/tag/2.0) and you'll need [7-zip](https://www.7-zip.org/download.html) to unpack it
> * Once you do unpack it far enough, you'll see two folders x32 and x64, these are the ones you want to extract
> * For this game, you'll need to get the files from the x64 folder
> * You will need to copy two files (not the entire x64 folder. If you do that, it won't work)
>   
>   * dxgi.dll
>   * d3d10core.dll
> * Paste those two files in the same folder that the game's exe file is at
> 
> Since this is the Async version, you must do a little bit more in the system's environment variables to have it perform (potentially) better.
> 
> > Set the environment variable DXVK_ASYNC=1
> 
> Easiest (or really semi-faster way) of doing it is:
> 
> * Type in Windows search "environment" -- you should see "Edit the system environment variables"
> * You will be taken to "System Properties"
> * Click on the Environment Variables radio button
> * Press the "New" button on the bottom box labeled "System Variables"
>   
>   * In "variable name" type in DXVK_ASYNC
>   * In "variable value" type in 1
>   
>   You might also want to keep those two folders of DXVK Async handy because there is a pretty good chance you'll be copying those two dll files rather often if some particular game that is DX9/10/11 and it doesn't perform the way it should.

Hey, thanks for the awesome and lengthy response. I tried it and sadly it did not help. Upon closer inspection it appears, that DMC 4 is still loading the dxgi.dll from the system.

**Comment by Eschryn** [comment]
Yes, that's the exact issue 👍

**Comment by BiZkViT96** [comment]
Have you tried this? https://steamcommunity.com/app/329050/discussions/0/1738884444460165730/

**Comment by Eschryn** [comment]
@BiZkViT96 Yes, I did. But it was only a temporary fix which would get me to play like five minutes or so (maybe more) and then it crashed because of the same issue. Besides after doing it a few times I got it into the state where I can't even get into the menu (it crashed already before)

**Comment by Eschryn** [comment]
Oh and a little sidenote: it runs in Linux under wine with dxvk on an Intel Arc. It's missing some other features (like some things just won't be rendered) but it doesn't crash.

**Comment by Arturo-Intel** [comment]
@Eschryn  Can you please try with 101.5330? I was able to play the game without any trouble.

**Comment by Eschryn** [comment]
@Arturo-Intel Hey, took a while to test this since I've switched to Linux. But Today I booted into my old Windows installation and the game seems to run very well. Thanks for fixing this.
