### ISSUE TITLE
while using two window in browser, one window will show black blocks

### ISSUE THREAD

**Issue by xGLANZEx** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#394]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

chrome ,opera gx

### Processor / Processor Number [Required]

amd ryzen 5 5600g

### Graphic Card [Required]

Intel arc a750 limited edition

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [X] 31.0.101.4514
- [X] 31.0.101.4502
- [X] 31.0.101.4499
- [X] 31.0.101.4382
- [X] 31.0.101.4369
- [X] 31.0.101.4335
- [X] 31.0.101.4314
- [X] 31.0.101.4311
- [X] 31.0.101.4257
- [X] 31.0.101.4255
- [X] 31.0.101.4148
- [X] 31.0.101.4146
- [X] 31.0.101.4125
- [X] 31.0.101.4123
- [X] 31.0.101.4091
- [X] 31.0.101.4090
- [X] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [X] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

didnt have that software 

### Description and steps to reproduce [Required]

use one or two browser at same time and and use different window for each tab then use youtube on it and try to drag them a little 

### Device / Platform

ryzen 5 5600g intel arc a750 LE   gskill trident 16gb ram 

### Crash dumps [Required, if applicable]

not available

### Application / Windows logs

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/129430439/15a6328a-afbf-4b9a-b350-4c01f23f0921

**Comment by Vivek-Intel** [comment]
Hi

We tried to simulate the issue with both A750 and A770 following description and video that you shared.
We were not able to [reproduce the issue at our end](https://www.youtube.com/watch?v=t5A31g9pSSE) so it might be specific to your system. We would like to know more information regarding the issue so can you please help share below information that can help us isolate the issue.

1: Can you try updating driver to 101.4644 which is latest one and check if issue occurs,
2: Can you share system details that you can obtain by running (Intel graphics command center --> click on Support icon in left panel -->System Diagnostic -->Generate report )
3: Can you try updating Windows ? or try Windows 11 and check if issue occurs ?
4: Are you using Windows snap feature, is it specifically occur only when you snap windows and try playing youtube or other websites?
5: Do you see issue when playing media player like TV  instead of browser
6: Can you try if it does repro when display is connected to AMD integrated GPU in system if its available  ?
7:  Is HDR on when issue occurs ? what is status if HDR is off ?
8: Can you run dispdiag (Open CMD -->Run Dispdiag -->collected dump generated)  and share it with us ?
9: Is it specific when display connected over HDMI or DP port ?

**Comment by Vivek-Intel** [comment]
Hi @xGLANZEx do you have any updates on above information with latest driver

**Comment by Vivek-Intel** [comment]
Hi @xGLANZEx  can you share above information with latest driver 101.4885

**Comment by Vivek-Intel** [comment]
@IGCIT can you help close this ticket.
