### ISSUE TITLE
No HDMI output if TV is off when pc is powered on

### ISSUE THREAD

**Issue by IGCIT** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#397]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Any

### Processor / Processor Number [Required]

i9-11900kb

### Graphic Card [Required]

A770 LE

### GPU Driver Version [Required]

- [X] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12073246/igcit_ssu.txt)

### Description and steps to reproduce [Required]

This is happening with all the TVs i have access to, currently using _Philips Tv 32PFS5603_
none of them has a DP port, so i'm always using HDMI

steps:

- TV is off, pc is off, hdmi cable is attached
- turn on the pc
- turn on the TV
- no video output

a hard reset of the device (press power to force shutdown) is required to restore video ouput **and** TV must be on before the pc is powered on

vbios 20.1053.0

**Comment by LancerDawg75** [comment]
It's a flaw between how the card was made and a combination of the Realtek RTD2173 PCON. 

You're not getting a true native HDMI port. It's Display Port that is converted to HDMI. This, unfortunately causes issues like that because there are times that I suffer from it on my system hooking it up through my HDTV that is probably far older than your TV.

This is also probably the reason why when connecting anything through HDMI (especially in the case of TVs) that you can't adjust color depth (10-12bit HDMI deep color) or color format (RGB Full or YCbCr 444).  I attempted to cover a lot of it in Issue #304 

I think a lot of it is that Arc (and it seems to extend to anything Xe based) can't tell what it is connecting to. I saw this in the logs of the Intel Graphics Command Center that when the application requests what the "DisplayInfo" is, it states that it can't find it. 

The solution that I found was to use a Active DP to HDMI adapter. It doesn't get rid of the issue completely, but it does reduce it quite a bit. I use a [CalDigit version 
](https://www.amazon.com/CalDigit-USB-C-HDMI-Video-Adapter/dp/B0BY3SW376?th=1). This has also helped with my issue when the display goes to sleep and loses its "focus" (ie: it no longer recognizes my "SonyTV", changes to "Wired Display", and sets an overscan. 

Really, as it stands now, you're out of luck using the HDMI port. Intel making a shortcut using the PCON instead of adding a true Native HDMI port was obviously the wrong decision. (it coul you want a less quirky experience, you're going to have to use the Display Port outputs on the GPU. That requires an adapter. 

I don't know if this can be fixed with a firmware update or if Intel realizes their mistake with Alchemist, and this gets addressed in Battlemage,

**Comment by Arturo-Intel** [comment]
@IGCIT did you try with DP?

**Comment by IGCIT** [comment]
waiting for the adapter

**Comment by IGCIT** [comment]
@Arturo-Intel it did not help, there is no output in any way unless TV is on **before** arc

**Comment by LancerDawg75** [comment]
Hmmm, I don't know much about Intel BIOSes, but can you check one more thing? Does your BIOS have ASPM settings? If so....is it enabled? Try setting it to disabled.

It's a way out in left field possibility. I only say this because on my platform (AMD B550) If I try to set the PM L1 SS to L1, L2, or L1+L2, I get nothing on screen but it boots to Windows normally.

If you don't have the option or have it disabled, then I'm not sure what the problem could be outside of settings between the TV (is there like a reset to factory defaults),or maybe a BIOS update for your motherboard (if a revision update states that there is GOP update along with it)or may try resetting the CMOS to defaults.

Actually, today I updated my motherboard's bios to AGESA 1.2.0.A, and the DP to HDMI adapter wouldn't work while the system had CSM enabled, but worked when using the HDMI port directly. Once I disabled CSM for full UEFI, then the direct HDMI port wouldn't show anything, but reconnecting the DP to HDMI adapter worked. 

Shit be weird, yo.

Apologies for throwing out so many "darts".

Perhaps, at the end of the day, it might be the card is bad or really Intel needs to address this issue with a firmware/VBIOS update.

**Comment by IGCIT** [comment]
disabled aspm, no output

**Comment by Arturo-Intel** [comment]
@IGCIT can you try to use CTRL + SHIFT + WIN + B when the TV doesn't have signal? 
This shortcut will restart the graphics drivers, maybe this would help to re-enable the output signal to your TV

-- r2

**Comment by IGCIT** [comment]
that works, i also noticed just now, there is a hdmi CEC option in bios, disabling it did the trick
