### ISSUE TITLE
A770 VRAM clock always at max frequency

### ISSUE THREAD

**Issue by stalker-svk** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#406]
### Application [Required]

all

### Processor / Processor Number [Required]

i5-13500

### Graphic Card [Required]

Arc A770

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

I noticed that VRAM runs always on max frequency even at idle, can you make it to dynamically adjust the VRAM clock according to load? underclock it at idle and run at max speed while gaming or other graphics intensive tasks, it can help reduce power consumption and heat generated

**Comment by LancerDawg75** [comment]
This I can get behind. I would definitely like to see this happen. Probably would take a VBIOS update.

**Comment by freak2fast4u** [comment]
Also interested

**Comment by montvna** [comment]
would love to see this implemented

**Comment by Gabriela-Intel** [comment]
Hey thanks all for chiming in to say me too! This really helps us gauge how many folks are interested in this so we can let the appropriate teams know. I'll work on passing along this feedback. :)

@IGCIT You can close this one

**Comment by stalker-svk** [comment]
why not close it rather when it will be already implemented?

**Comment by Gabriela-Intel** [comment]
Good question! We love getting feedback but the "problem" is that first, even though the request is a great idea, we can't guarantee that the teams will be able to take on the task or agree to implement it due to a variety of reasons (managing priorities, workload, other issues & feature requests, etc.).

Not only that but it's most common that it takes quite a while (I'm talking about _at least_ 6+ months) for the team to make the changes, implement it, and test it once they decide to move forward with the feature.

We're tracking this internally and making sure to the right team though.

Thanks again for your feedback!

**Comment by onlymash** [comment]
I also have the same problem with a770m on NUC12SNKi72. Will keeping the VRAM at the maximum frequency cause the life of the VRAM to decrease? If it is a laptop, will the battery life be shortened?

**Comment by stalker-svk** [comment]
yes it decrease battery life, for example nvidia cards can go to 130 mhz core and 200 mhz memory when idle

**Comment by onlymash** [comment]
Just like Ethereum mining in the past, the vram was always running at the maximum frequency or even overclocked. The vram aged very quickly. Basically, the vram was damaged before the GPU core.  So I am very worried about the vram life of arc gpu.
