### ISSUE TITLE
Display driver resets every time Virtual Desktop is connected/disconnected

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#425]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Virtual Desktop (Meta Quest)

### Processor / Processor Number [Required]

Intel Core i5-13600K

### Graphic Card [Required]

Intel Arc A770 16GB LE

### GPU Driver Version [Required]

- [X] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [ ] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Intel SSU 11.08.2023.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12322852/Intel.SSU.11.08.2023.txt)

### Description and steps to reproduce [Required]

Connect your Meta Quest 2 to the PC with Virtual Desktop, and experience the black screen (true black screen, not just the GPU sending black video. I know this because first my display isn't OLED yet in the black screen I see pure blacks, and seconds because when the black screen and, I see "DP" in the top right corner of my display)

### Device / Platform

ASUS Prime Z790-P WiFi D4

### Application / Windows logs

Logs of the Event Viewer about the crash of Desktop Window Manager (dwm.exe), super hard to find so I hope it'll be useful https://1drv.ms/f/s!AmnzYyniwxuygaN2DeUkjTH_d0Y4Og?e=sVHjFf

**Comment by Karen-Intel** [comment]
Hi @TheWonderfulTartiflette thank you for your report.
However, Intel Arc graphics support for VR technology/headsets continues to evolve as we ramp our products and add updates to our software stack, so this case will be marked as FUTURE for the time being. 
A case has been created internally and will reopen it and this thread once we have an update about VR Support in ARC.
@IGCIT can you help us close this one? TY

Karen

**Comment by TheWonderfulTartiflette** [comment]
Sure I can already close it, thanks, I do hope VR will be added soon because even with a 3rd party app we can't play any VR game at all

**Comment by PetanoCZ** [comment]
I have similar issues. 
HW - Serpent Canyon
OS - Windows 11
Driver - 4824
VR - Platform - Windows Mixed Reality - HDM - Oddyssey + with Reverb G2 controllers
My description:
WMR portal opens fine and works fine
Working Games: Beat Saber, Fruit Ninja VR, Job Simulator, Arizona Sunshine, TheBlu, Richi's plank
Somewhat working: Alyx VR - I have to stay very still at the beginning to get to initial menu and start game. If not game crashes or get stuck on press trigger "rocks" scene. After that it plays fine.
Huge glitches: Fallout 4 VR - one eye has huge texture mapping issues (on most recent driver 4824 game won't start at all). Video is attached. Steam VR home is flickering and basically not working. Video attached.
Not working games (don't launch at all and crash back to WMR portal or Void): The Lab, Portal Stories VR, Skyrim VR, Fallout 4 VR (at driver 4824 - not sure which driver broke it but was launchable with issues on older driver)

I know this issue is closed due to pending action on VR compatibility. Once re-opened I am happy to provide more troubleshooting.

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/145778385/3aa56604-a1fc-45f9-aed2-a38e5e725e77

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/145778385/57c2ffc9-2307-4cdf-a7b1-cb8c5a21993c
