### ISSUE TITLE
Unable to upgrade [from 31.0.101.4502 to .4676] drivers via Intel installer

### ISSUE THREAD

**Issue by feamsr00** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#492]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Installer

### Processor / Processor Number [Required]

Intel® Core™ i5-4670K CPU @ 3.40GHz

### Graphic Card [Required]

 Intel® Arc™ A750 Graphics

### GPU Driver Version [Required]

- [X] 31.0.101.4676
- [ ] 31.0.101.4672
- [ ] 31.0.101.4669
- [ ] 31.0.101.4644
- [ ] 31.0.101.4578
- [ ] 31.0.101.4577
- [ ] 31.0.101.4576
- [ ] 31.0.101.4575
- [ ] 31.0.101.4514
- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[Detailed-System-Report.html.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12564160/Detailed-System-Report.html.txt)
[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12564226/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Attempted to upgrade driver from 31.0.101.4502 to 31.0.101.4676. Error below generated each time.
(Reboots have not helped)

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/983484/d97f2d25-687f-42db-8d46-f72a8f6b7464)

### Application / Windows logs

Installer log
[IntelGFX.log](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12564165/IntelGFX.log)

**Comment by IGCIT** [comment]
hi @feamsr00 

it seems installation is failing because there is not enough space on disk

please try to free up some space and try again, or, try a clean install with [DDU](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html) (it should removed previous driver and thus free some space)

**Comment by IGCIT** [comment]
nice :)

if you want to make a feature request, please open a new issue (it is easier to track them)

the errors can be found in installer log you attached (IntelGFX.log)
![Screenshot_20230912_090737](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/76787191/96a43783-4c42-4c3b-a891-99ab6163fe46)

closing since this is solved
