### ISSUE TITLE
Desktop PC dual GPU - A770LE high idle power consumption when using iGPU as primary GPU

### ISSUE THREAD

**Issue by stalker-svk** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#569]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

N/A

### Processor / Processor Number [Required]

i5 13500

### Graphic Card [Required]

A770 LE + UHD 770

### GPU Driver Version [Required]

31.0.101.4900

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13182359/SSU.txt)

### Description and steps to reproduce [Required]

when using Arc A770 as secondary GPU with integrated UHD 770 as primary GPU the Arc control center shows A770's power consumption when idle about 1-2 W, also power meter connected to wall power reads about 35W which is the power consumption of whole PC but after a while the arc control center shows A770's power consumption as "-" (that means the card is completely turned off) but the wall power meter start to read about 70W (like the A770 is using 40W - just like without ASPM but ASPM is enabled and working), can you please solve this ?

### Device / Platform

desktop PC with full ASPM L1 and REBAR support

**Comment by Karen-Intel** [comment]
Hey @stalker-svk what is the application or program you are using and choosing iGPU instead of DGPU to test power consumption?
Please verify the following[ information.](https://www.intel.com/content/www/us/en/support/articles/000092564/graphics.html) and confirm you're using the setting for 'Maximum power savings'

Thanks

Karen

**Comment by stalker-svk** [comment]
> Hey @stalker-svk what is the application or program you are using and choosing iGPU instead of DGPU to test power consumption? Please verify the following[ information.](https://www.intel.com/content/www/us/en/support/articles/000092564/graphics.html) and confirm you're using the setting for 'Maximum power savings'
> 
> Thanks
> 
> Karen

no applications running, just being idle in windows

**Comment by Karen-Intel** [comment]
Okay so, can you clarify how you set up your iGPU as primary?  Do you disable ARC in Device manager and read the power draw in ARC Control and in your wall power meter?

TY

Karen

**Comment by stalker-svk** [comment]
> Okay so, can you clarify how you set up your iGPU as primary? Do you disable ARC in Device manager and read the power draw in ARC Control and in your wall power meter?
> 
> TY
> 
> Karen

just connect monitor to motherboard output instead of GPU output and then you will have 2 GPUs available and your iGPU will be the primary GPU (just like nvidia optimus on laptops), you don't need to disable anything in device manager, in windows settings (system->display->graphics) you can choose what app will run on iGPU and what app will run on dGPU, but while you are idle in windows, you use the iGPU and arc should be turned off by ASPM

**Comment by freak2fast4u** [comment]
Well well well ... I have some very interesting findings (the problem IS reproduced on my end, I hope I can clarify what might be going on) : 

Same conditions as described above, with ASPM enabled in BIOS, but no matter how I configure ASPM PCIE control mode, the same thing happens (Auto, L0s, L0s+L1, no change)  : 
- The PC boots, the Arc GPU uses 0W and telemetry looks normal, the card is both "on" and "idle" or so to speak.
Here's what it looks like at first, with a total system power draw of 75W (idling in windows with nothing open) : 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/6f2fb384-a94c-409c-a4b9-ccb4d92c48d0)

At this point, all good right ?

Well, a few moments later, while I'm not even touching the keyboard or mouse, it goes south ...
![2023-11-07 22_12_17-Paramètres](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/3486369/c7cd84d6-69c5-490a-9ee7-5e749264f999)
This seems to be what OP described, and indeed, at that precise moment, the total system power draw goes back up to 100W, which is generally where it's at when power savings are disabled ...
But then, something even wierder happens ... I opened Firefox, and intel arc control overlay telemetry came back showing 0W on the GPU core, and the total system power draw went back down to 75W.

As of now, the A770 card and/or drivers are in a loop of "working" and "not working", using 0W one moment and using 45W the next moment (even though telemetry shows nothing of it).
Now, I was doing nothing for a while, and decided to open GPU-Z just to run a quick graphics test and see if I could wake the card up. As soon as I opened GPU-Z, the overlay came back (not even running the test yet) and power usage came down ... for roughly a minute ... and it went away again, and the watts went up again. 

In the end, I totally confirm OP's report, that power usage goes up and at the same time telemetry becomes unavailable.

In fact, I went to far as to film the whole damn thing because I couldn't believe it either ... (private video on youtube) : https://www.youtube.com/watch?v=mbSijfrMh6E

**Comment by stalker-svk** [comment]
if this worked correctly it would be even better power saver than ASPM because the card can be turned off completely when not using graphics intensive apps like games...when doing the same thing with nvidia card, when it shuts off completely, the wall power draw does not rise and the card is really turned off

**Comment by stalker-svk** [comment]
if this worked correctly, it would be even better power saver than ASPM

**Comment by stalker-svk** [comment]
intel, any progress on this issue?

**Comment by Karen-Intel** [comment]
Hi all, sorry for the late reply, we're actually having lots of fun with this one xD (kidding)
I will be sharing my internal report number soon. 

Something I haven't observed with the latest driver is the GPU showing -null- value in idle. Could someone else confirm?
With ASPM in Auto it has been in 1-2% activity in idle state, telemetry seems to be behaving better

Thanks! Talk to you soon

Karen

**Comment by Karen-Intel** [comment]
> Hi all, sorry for the late reply, we're actually having lots of fun with this one xD (kidding) I will be sharing my internal report number soon.
> 
> Something I haven't observed with the latest driver is the GPU showing -null- value in idle. Could someone else confirm? With ASPM in Auto it has been in 1-2% activity in idle state, telemetry seems to be behaving better Also, if you could share your wattage consumption with this latest driver v5084 that would be amazing :)
> 
> Thanks! Talk to you soon
> 
> Karen

Hi guys any update to my last comment?

Thanks

Karen

**Comment by Karen-Intel** [comment]
Hey @IGCIT can you help close this one out?
No updates since February 8th 

Karen

**Comment by stalker-svk** [comment]
I want to reopen this issue as the problem is still present in newest driver 6557, sorry for late reply but I have tested it only now, problem is the same, when dGPU shuts off completely, its power draw comes to 40W while monitoring software shows 0W

**Comment by ghar3344** [comment]
I've been able to replicate these issues with a Sparkle B580 Guardian model. While the issue does not appear to be fixed with the latest available drivers, there are some workarounds that I have noticed. I have the B580 paired with a an Ultra 7 265K on an ASRock B860i mini-ITX board. I am primarily using the integrated GPU for most tasks (monitor plugged into the motherboard HDMI port) as most of my workload is light office and web based tasks with only occasional need for gaming or AI workloads.

To overcome the weird idle behaviour- setting the screen timeout in power settings and allowing the monitor to turn off this and then waking it by shaking the mouse seems to resolve this issue for the rest of the session. The whole PC idles around 25w this way with ASPM enabled and maximum Link state power savings.

Another way is to completely disable the B580 GPU in device manager at which point the card uses very little power- you have to re-enable before running heavy applications needing the B580 GPU of course. With this method, the whole system idles at around 16 watts (similar to what it did before installing the discrete GPU) but the side effect is that the fans on the B580 are constantly running at a low speed and do not completely stop but this does not actually create all that much noise.

While these workarounds are not ideal, it does give some options for those who want to primarily use the integrated graphics for power savings until a solution is found by Intel/board partners. Please try this out with the other models of the B580 you have share your findings as it may help other with similar issues. All the power readings are measured at the wall.

**Comment by GeoffreyAA** [comment]
@ghar3344,

As detailed in #1172, I have the problem when the monitor is connected to the GPU. In essence, when the GPU goes "off," power consumption shoots up because ASPM is no more maintained. My solution is to keep the display signal on and physically turn off the monitor.

**Comment by stalker-svk** [comment]
> [@ghar3344](https://github.com/ghar3344),
> 
> As detailed in [#1172](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/1172), I have the problem when the monitor is connected to the GPU. In essence, when the GPU goes "off," power consumption shoots up because ASPM is no more maintained. My solution is to keep the display signal on and physically turn off the monitor.

but this is about having monitor connected to integrated GPU and Arc being the secondary GPU that should engage only when needed...if it worked correctly, the power consumption will be even smaller than having dGPU only with ASPM

**Comment by GeoffreyAA** [comment]
> > [@ghar3344](https://github.com/ghar3344),
> > As detailed in [#1172](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/1172), I have the problem when the monitor is connected to the GPU. In essence, when the GPU goes "off," power consumption shoots up because ASPM is no more maintained. My solution is to keep the display signal on and physically turn off the monitor.
> 
> but this is about having monitor connected to integrated GPU and Arc being the secondary GPU that should engage only when needed...if it worked correctly, the power consumption will be even smaller than having dGPU only with ASPM

I hear what you're saying. I do think it's the same principle at work: that of not having the dGPU output a display signal, leading it to go into, presumably, an even lower power state than ASPM, but something goes wrong and power shoots up.

**Comment by stalker-svk** [comment]
> > > [@ghar3344](https://github.com/ghar3344),
> > > As detailed in [#1172](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/1172), I have the problem when the monitor is connected to the GPU. In essence, when the GPU goes "off," power consumption shoots up because ASPM is no more maintained. My solution is to keep the display signal on and physically turn off the monitor.
> > 
> > 
> > but this is about having monitor connected to integrated GPU and Arc being the secondary GPU that should engage only when needed...if it worked correctly, the power consumption will be even smaller than having dGPU only with ASPM
> 
> I hear what you're saying. I do think it's the same principle at work: that of not having the dGPU output a display signal, leading it to go into, presumably, an even lower power state than ASPM, but something goes wrong and power shoots up.

problem starts when the card goes completely off, then the power consumption of card ramps up to 40W, as long as the card is "only" sleeping, its power consumption is about 0-1 W. so Intel should implement something that prevents the card from going completely off (as this also cuts the ASPM off for the card) and keep it in this state when not used.

**Comment by ghar3344** [comment]
@GeoffreyAA 

I agree, I think it's effectively the same issue- when there is no load on the GPU (either when the display signal is cut by Windows as in your case or there are no programs running on the discrete card as in mine), it seems to go into a complete sleep mode which breaks the ASPM (with increased power draw and heat generation as we've observed)- I think this requires a driver-level fix from Intel or the board partner which built the card. Looking through #1172, we can at least determine that the issue is not motherboard related as this can be replicated on my ASRock motherboard as well.

@stalker-svk 
If you're still having the same issues mentioned, maybe worth trying the workarounds I suggested if it's practical for you. The core issue seems very similar so the workaround might also be applicable to the A770.

**Comment by stalker-svk** [comment]
> [@GeoffreyAA](https://github.com/GeoffreyAA)
> 
> I agree, I think it's effectively the same issue- when there is no load on the GPU (either when the display signal is cut by Windows as in your case or there are no programs running on the discrete card as in mine), it seems to go into a complete sleep mode which breaks the ASPM (with increased power draw and heat generation as we've observed)- I think this requires a driver-level fix from Intel or the board partner which built the card. Looking through [#1172](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/1172), we can at least determine that the issue is not motherboard related as this can be replicated on my ASRock motherboard as well.
> 
> [@stalker-svk](https://github.com/stalker-svk) If you're still having the same issues mentioned, maybe worth trying the workarounds I suggested if it's practical for you. The core issue seems very similar so the workaround might also be applicable to the A770.

currently the best power-friendly workaround is to use dGPU only with monitor not turning off by windows but manually via power button, but when there is any GPU related activity such as watching youtube videos, the card uses about 40W. this is where iGPU consumes only few watts

**Comment by GeoffreyAA** [comment]
@ghar3344 and @stalker-svk,

Good observations and analyses. Should we perhaps open a new ticket? Clearly, it is a real issue, either firmware- or driver-related, though I wouldn't rule out Windows.

**Comment by ghar3344** [comment]
@GeoffreyAA Sure, are you happy to open and I can also post what I've found. I don't think that this is purely a Windows issue as I dual boot with Ubuntu which is officially supported by Intel and there is a similar issue whilst using the integrated GPU as the primary device. I have to leave Mission Center (a system monitor) running in the background which polls the B580 to keep it awake- as soon as this program is closed, you hear coil whine from the B580 and the full system power usage increases by around 30 or so watts (same as what I'm seeing on Windows).

@stalker-svk 
If you're not using the discrete card often, try disabling it through Device manager and plug your display cable into the motherboard. This way, I have been able to use the integrated GPU and even when watching 4K videos on YouTube through the Edge browser, the whole PC is only drawing around 18-20 watts at the wall whereas if  I connect the display cable into the B580 and try this, just the card itself will easily draw this much power. You just have the hassle of re-enabling the card through Device manager again when you want to run graphically intensive tasks on it and the GPU fans are constantly running at a very low speed but for me, the power savings (whole system power draw is effectively halved) for the more than 90% of time I use the PC for makes this worth it.

**Comment by GeoffreyAA** [comment]
Hello @Felipe-Intel,

In light of the recent comments, do you recommend opening a new ticket? I know you put a lot of work into #1172, for which I am grateful, and do not wish to add unnecessary work to the team. Thanks.

**Comment by Felipe-Intel** [comment]
Hello all. If this is affecting a lot of users, then yes. It is fair to open a ticket. 
You will need to provide clear and consistent repro steps, along with system configurations and tools/method used for measuring. 
Just keep in mind that to have reliable measurements, those should be done with external equipment (hardware meters, something similar to [this one](https://www.thermal-grizzly.com/en/wireview-gpu/s-tg-wv-p18n)). This does not mean that you have to buy one, instead it means that when we measure with such tools, there is a chance we get different results than yours. Also, wall outlet meters won't provide reliable information as they are measuring the whole system power consumption, not only the card's. 
Measuring with software tools will keep the card awake.

**Comment by ghar3344** [comment]
Thank you both @GeoffreyAA @Felipe-Intel . I'm quite busy with work at the moment but will open a ticket at some point in the next couple of weeks once I've had  time to do some more methodical testing. I dont think I can get dedicated hardware monitors but will try and keep variables to a minimum with the kit I have.

**Comment by GeoffreyAA** [comment]
I tried putting together a methodology. Improvements are welcome. For my part, I don't possess a hardware tool. Temperature could be used as a proxy for power draw.

### Hypothesis
When the GPU is idle and its display engine off, it tries to enter a deep sleep. Inadvertently, the [ASPM L1 state](https://www.intel.com/content/www/us/en/support/articles/000092564/graphics.html) is lost, making power draw similar to disabling ASPM.

_Method 1: Display engine off; iGPU driving monitor_
1) Turn off ASPM settings. Leave the GPU idle but awake, perhaps through polling software or low load. Measure the Total Board Power (TBP) using specialised hardware, giving **ASPM_OFF**.

2) Turn on all ASPM settings. Follow same steps as (1) to measure TBP, giving **ASPM_L1**.

3) With all ASPM settings enabled, leave the GPU idle and unengaged. Measure TBP, giving **DEEP_SLEEP**.

- If DEEP_SLEEP is equal to ASPM_OFF or greater than ASPM_L1, the hypothesis is true.
- If DEEP_SLEEP is less than or equal to ASPM_L1, the hypothesis is false.

**Comment by bglee5268** [comment]
This problem happens to my system too. 
Here's the system information and procedures to reproduce it (and hopefully workaround too)

## System Information 
* Hardware
  * CPU: 5700G
  * Motherboard: ASUS X370 Prime Pro
  * BIOS: ASPM L0s and L1 enabled
  * GPU : Intel A770 LE (PCIE 3.0 X8 due to the CPU spec)
* Software 
  * OS: Windows 11 25H2 (10.0.26200.7171)
  * Intel Graphics Driver : 32.0.101.8250 (Nov 7, 2025)
* Power Measurement
  * TAPO P110M (Smart Switch) Wall power-meter
  * Home Assistant with P110M connected
  * Monitoring value reading is in real-time (but a little bit slow like 2~3sec) 

## Video capture
https://github.com/user-attachments/assets/231b5915-24ca-4f38-8b40-ff7052297365

## Steps
* Connect monitor to IGPU port (motherboard's displayport connector) 
  * 'A770 LE' has no connected displays (display is only connected on IGPU)
* Set power plan to 'Power saver'
* Launch GPU-Z and wait ASPM is applied
* Measure power consumption
* 'P110M,2' is current system's TAPO P110M smart switch 
* ASPM applied and GPU goes to sleep 
* **after some time (58s in video), monitoring software not reading the value and power consumption goes up from 51.5 to 78.9**
* (in 1:33s) clicked GPU-Z window (set application to foreground window) 
* (in 1:40s) Power consumption and monitoring value changed to normal idle state

## Notes 
* If problem occurs, Set monitoring application as active window (by alt + tab) again will change it to normal idle state (monitoring value too)
* **In my case, the reason not using DGPU as primary display** is to save unnecessary power consumption 
  when using system in light load (browsing, youtube, documenting, ...) with multi displays connected. 
  DGPU is only needed for gaming, development and processing AI inference work load. It saves 20~30w consumption easily.
* **memory clock is stuck to maximum (even when no display is connected in DGPU)**
  * when single display (4K 60hz) is connected in DGPU and IGPU is not used, memory clock goes down properly.
  * assume intel display software detects IGPU's connected display as DGPU's display and it causes problem
 
## Workaround to solve the problem (temporally)
* **Get a HDMI dummy plug and connect it to A770's HDMI port.**
* **Turn off the dummy plug's screen in display settings and use IGPU as primary display** 
* It will make A770 sleep with normal idle state. Quick hack but it works for my system ;-)

Hope developers find the way to fix the problem properly by software update.
