### ISSUE TITLE
Why have Gigabyte video cards not received a BIOS firmware update for the second time?

### ISSUE THREAD

**Issue by Noobachyo** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#578]
### Application [Required]

bios version

### Processor / Processor Number [Required]

i3-10105f

### Graphic Card [Required]

Intel Arc A380

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [ ] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1
- [ ] Windows 10 22H2
- [ ] Windows 10 22H1
- [ ] Other (Please specify)

### Describe the feature [Required]

Why have Gigabyte video cards not received a BIOS firmware update for the second time?

**Comment by abrfilho** [comment]
The firmware provided on the latest driver, 4952, was only for Intel LE models.
As for the first firmware, I don't have an answer.

**Comment by Karen-Intel** [comment]
@Noobachyo have you checked with Gigabyte support?
I do not see the Intel ARC A380 Card in their[ Graphics Card support page](https://www.gigabyte.com/Support/Graphics-Card), and as we have informed before, driver releases have a cadency that, after the manufacturer approves, can be deployed to their  cards. That's why the Intel LE cards get the FW update first 
I wonder why the model is not in their support page, would be worth to check why there's only Intel 740 in their page.

Karen
