### ISSUE TITLE
The Dark Pictures: Man of Medan Crash after start

### ISSUE THREAD

**Issue by Rebusmind** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#67]
#### Checklist [README]

- [X] Device is not undervolted nor overclocked.
- [X] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [X] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
The Dark Pictures: Man of Medan
---
#### Game Platform [Required]
- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]
i7-1165
---
#### GPU Driver Version [Required]
- [X] 30.0.100.9667 (*latest*)
- [ ] 27.20.100.9616
- [x] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)

---
#### Description and steps to reproduce [Required]

1. Start the game
2. The loading icon and a loading bar at the bottom of the screen appear
3. After 1 or 2 seconds the game closes (silent crash)

---
#### Device / Platform [Optional][Recommended]

GPD Win 3

---
#### Game Settings [Optional][Recommended]

Default values (first time booting the game)
---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by Rebusmind** [comment]
Btw. I tried it both with the latest stable driver and with the beta driver.

**Comment by estebanr863** [comment]
Hi @Rebusmind

We were able to reproduce this issue and found that its root cause to be on the game side. We have already escalated this issue to the game developer, but now is up to them to fix the issue.

The root cause was found to be an older version of OpenSSL that usually triggers on games running on certain versions of Unreal Engine. You can find more details and a possible workaround in the article [OpenSSL* SHA Crash Bug Requires Application Update](https://www.intel.com/content/www/us/en/developer/articles/troubleshooting/openssl-sha-crash-bug-requires-application-update.html).
