### ISSUE TITLE
 Battledroid OpenGL renderer crashes

### ISSUE THREAD

**Issue by ewahl-osc** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#675]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Battledroid

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

AMD Ryzen 5800x3xd

### Graphic Card [Required]

predator A770

### GPU Driver Version [Required]

31.0.101.5085

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/13932916/ssu.txt)

### Description and steps to reproduce [Required]

Game has constant crashes from OpenGL not properly rendering all items on screen.  Devs have passed along a steam Key for Intel use., please reach out to me in email and I will forward.   
We're used RenderDoc and driver is crashing/exiting before we can even get any decent crash information.
Frame captures take exceedingly long time (normal GPU is ~1 or 2 seconds, ARC is 5-15 seconds in OpenGL.
No 3D items are being rendered. 

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

all settings have the issue

### Crash dumps [Required, if applicable]

none.  Even RenderDoc is not getting caps as the driver is exiting before anything useful can be obtained.

**Comment by ewahl-osc** [comment]
Crash: select many of the menu options, or just mouse-over the large icons on the lower left.  Anything that does 3D.

**Comment by Arturo-Intel** [comment]
@ewahl-osc I didn't see any email in your github profile, please send me an email (you can check it in my profile) so we can start debugging this. 

:)
-- r2

**Comment by theagentd** [comment]
Hello! I'm the graphics engine developer for Battledroid.

Since the very beginning, our game has unfortunately been unplayable on Intel due to this driver issue. It would be greatly appreciated if we could get some assistance to get the game to run on Intel GPUs!

@Arturo-Intel I've sent you an email with a Steam key for the Battledroid alpha. The error is trivially reproduceable by simply starting up the game and pressing basically any of the buttons on the main menu.

We would love to have this fixed, as we predict that a significant portion of our players will be trying to play our game on Intel GPUs, especially integrated ones.

Here are some "hints" for some of the more unusual features that we use that have caused issues with Nvidia/AMD drivers in the past, that we have had to work around or otherwise account for:
- We use exclusively use GPU-driven rendering for rendering 3D models, meaning we only do a single glMultiDrawElementsIndirectCount() call for each shader in each render pass. The draw call parameters and the draw call count values are both generated using compute shaders, with the draw call count being an atomic counter.
- We use order-independent transparency for all our transparent geometry. This involves storing fragments in per-pixel linked lists using atomic adds and exchange operations.
- We use dual source blending for one of our fullscreen passes related to volumetric lighting.

Please let me know if there's any additional information that you need regarding this! I am able to provide code and such as needed. :)

**Comment by theagentd** [comment]
Extra info: By adding ```-Ddebug=true -DgpuMarkers=true``` as command line arguments to the game, you can enable human-readable debug markers (glPush/PopDebugGroup()) for the OpenGL commands we do.

When there is 3D rendering going on, it will appear under Frame --> update() --> doUpdate() --> VoxoidScene 0 --> RenderCamera 1. Unfortunately it seems to crash somewhere in there. I can provide a reference RenderDoc capture on my AMD card if it would help.

**Comment by Arturo-Intel** [comment]
>We're used RenderDoc and driver is crashing/exiting before we can even get any decent crash information.

@ewahl-osc @theagentd Can you check if your renderdoc crash is still present on 101. 5330 (there was a fix no so long ago for this sw)

BTW your discord links on your main page are invalid/broken, wanted to contact you guys from there.

**Comment by theagentd** [comment]
> Can you check if your renderdoc crash is still present on 101. 5330 (there was a fix no so long ago for this sw)
We were able to take RenderDoc captures (although it was very slow) of the main menu, which has no 3D rendering at all. However, because the driver simply silently exits as soon as we try to do any 3D rendering regardless of if we run the game through RenderDoc or not, we're unable to take captures of the issue specifically.

> BTW your discord links on your main page are invalid/broken, wanted to contact you guys from there.
Sorry about that, we recently had our community Discord server breached and taken over by hackers. :( I'm the only one working on the graphics engine on our team of 3 people, so feel free to just add me directly on Discord. My username is the same as here.

**Comment by Arturo-Intel** [comment]
> We were able to take RenderDoc captures (although it was very slow) of the main menu, which has no 3D rendering at all. However, because the driver simply silently exits as soon as we try to do any 3D rendering regardless of if we run the game through RenderDoc or not, we're unable to take captures of the issue specifically.

Yeah, I notice the lag when taking captures with RenderDoc. I will open a case for this behavior. I will try to capture the data using other methods. If I am lucky, I will share the info with you.

One thing I notice when taking a capture on the main menu is this message error:
`description Error has been generated. GL error GL_INVALID_ENUM in IsEnabled: (ID: 3525876922) Generic error`

I am not saying this is the root cause of the issue, but it was something that capture my attention.
Do you get this error with Nvidia/AMD GPUs?

**Comment by theagentd** [comment]
As far as I know, we don't have a single call to glIsEnabled() in our entire code base. We don't see any OpenGL errors on other GPUs/drivers at all.

**Comment by Arturo-Intel** [comment]
FYI @theagentd @ewahl-osc  
the internal report number is: 14021705888

**Comment by ewahl-osc** [comment]
I understand there was perhaps a fixed demonstrated at some point.  Any idea when we might see it in the released drivers?

**Comment by Arturo-Intel** [comment]
@ewahl-osc this particular issue is fixed since 101.5518. Can you please re-test? (if you have a way to do it)
I am in constant communication with @theagentd to fix this issue (and others that come up)
There were some changes made by the dev to WA the problem, but now the support for the requested OpenGL function is already in our drivers :)

--r2

**Comment by ewahl-osc** [comment]
Testing has shown no crashes.  Feel free to close this issue.
