### ISSUE TITLE
Assassin's Creed Syndicate crash

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#744]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Assassin's Creed Syndicate

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [X] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc A770

### GPU Driver Version [Required]

31.0.101.5379

### Other GPU Driver version

31.0.101.5333

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[SSU_20240321.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14695332/SSU_20240321.txt)

### Description and steps to reproduce [Required]

Just updated to the latest driver v5379 and this bug appeared. The game can launch but crashes as soon as the main menu shows up. 

I reverted the driver back to v5333 and the problem was gone.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

Environment Quality: Very High
Textures Quality: High
Shadows Quality: PCSS
Ambient Occlusion: HBAO+
Anti-Aliasing: FXAA

**Comment by EstebanIntel** [comment]
Hi @Susie1818,

I tested this on a 13700K + A770 system and I'm not seeing any crashes (please see the video below). Can you try performing a clean install of the drivers and verifying the game files from the Ubisoft Connect client?

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/87549650/51afd070-ed0e-4769-a4df-4db53c7e0c79

**Comment by Susie1818** [comment]
@EstebanIntel 

I guess this case is a little bit more complicated. I found it also sometimes crashes even after driver rolled back to v5333. The key point is that my specific model of A770 is Acer Predator BiFrost, and during the driver update of v5379 it flashed VBIOS firmware, which didn't occur with my intel A750 Limited Edition model.

I guess it has something to do with the firmware update.

If you want me to further investigate this issue, I need to first roll back to a certain older driver version that flashes an older firmware. And I am not pretty sure which version does so.

**Comment by EstebanIntel** [comment]
@Susie1818,

Please note that even if you install an older driver version, that won't roll back your FW, only your driver. The installer is set to never rollback FW updates.

Also, please note that the driver installer always says that it might install a FW update, even if your card is already on the latest FW. This is because we are rolling out the FW update in a controlled manner, only adding some models of Arc cards on each driver version. So, the installer needs to show that message to all users, as for some user's Arc cards it might be the first time getting the FW update on a specific driver version. Getting this message during a driver installation doesn't necessarily mean your card's FW will be updated; that is only the case for new card models been added to the FW update enabled list on each specific driver version.

That been said, the Acer Bifrost A770 was enabled for FW update several months ago. Can you please verify your card is on FW version 20.0.1068 (which is the exact same I used on my test above)? You can check the FW version in ArcControl -> Settings -> System Info -> Hardware -> IFWI (V-BIOS).

Finally, can you please capture the memory dump of your crash and add it here? This will help us understand the possible causes of your issue. You can find the instructions on how to get these memory dumps in the section "Crashing/freezing issues/BSOD" of [https://community.intel.com/t5/Intel-ARC-Graphics/Need-help-Reporting-a-bug-or-issue-with-Arc-GPU-PLEASE-READ-THIS/td-p/1494429](https://community.intel.com/t5/Intel-ARC-Graphics/Need-help-Reporting-a-bug-or-issue-with-Arc-GPU-PLEASE-READ-THIS/td-p/1494429)

**Comment by Susie1818** [comment]
@EstebanIntel 

> Please note that even if you install an older driver version, that won't roll back your FW, only your driver. The installer is set to never rollback FW updates.

No, you're wrong. When I was dealing with [this issue](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/580#issue-1977558897) an older driver installer did flash the firmware back to an earlier version.

> please note that the driver installer always says that it might install a FW update, even if your card is already on the latest FW. ...... Getting this message during a driver installation doesn't necessarily mean your card's FW will be updated; ......

I know what you mean, but I have always been monitoring the detailed process of every driver update. Click on "Show details" during installation and you can see what the installer is actually doing in real time. That's why I can differenciate that the v5379 installer did have updated the firmware on my Acer A770 but not on my intel A750 LE.

Moreover, I don't know if you are aware of this - even with exactly the same FW version number (eg. 20.0.1068) shown in the ArcControl, it is still possible different firmware images. Don't ask me why. You should go ask the driver engineers why they decided to do so. So far I haven't tried to manually flash the VBIOS myself, but I know people do have tried and done that (eg. [this thread](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/430#issue-1852348683)). I think it's also doable for me, but I simply think it's too troublesome. Arc GPU does offer great value, in the beginning when you pay the tag price to purchase it, but the time it has costed me to troubleshoot .... I don't know, how to evaluate the time I have spent on it?

**Comment by EstebanIntel** [comment]
@Susie1818,

Please only use driver versions from [Intel® Arc™ & Iris® Xe Graphics - Windows*](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). The official drivers CURRENTLY available in this site DO NOT rollback FW version. Also, please note that using alternate methods to install FW on Arc cards will void your warranty and is not supported.

Please gather the memory dump as requested in my previous post, as this is the best way to identify the possible root cause of your issue.

**Comment by Susie1818** [comment]
@EstebanIntel 

So you have put an emphasis on "CURRENTLY available" drivers. I understand now. I am pretty sure driver v4826 would overwrite the firmware with an earlier version because I have done that before. Thanks for telling me that, so I don't have to do that again.

As for the memory dump, I will try to do that when I have plenty of time. Probably not very soon. Sorry about that.

**Comment by Susie1818** [comment]
@EstebanIntel 

Driver v5382 seems to have resolved the issue. I have tried launching this game several times and it didn't seem to crash anymore. However, I noticed the efficiency of DX11 driver in this game became even worse than v5333. When compared with DXVK, v5333 DX11 driver could render at exactly the same framerate with only a disadvantage of consuming more CPU power, while v5382 DX11 not only consumes even more CPU power than v5333 but also renders lower FPS.

I don't know exactly what the driver engineers have done to the DX11 driver in v5382, but hopefully you can help forward this message to them so that they can be aware of it. Thanks.

**Comment by EstebanIntel** [comment]
Hi @Susie1818, 

I'm glad that the issue is no resolved for you. I will forward your feedback on the game performance to the dev team.
