### ISSUE TITLE
Intel Arc A750 AI error on topaz while gpu is selected

### ISSUE THREAD

**Issue by QuintN16** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#774]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Topaz Video AI v4.1.2 (x64)

### Processor / Processor Number [Required]

AMD 7800x3d

### Graphic Card [Required]

Intel Arc a750

### GPU Driver Version [Required]

31.0.101.5445

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

![Screenshot 2024-04-30 233345](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/168619196/7f084641-523f-4f2d-9919-cd7ce104f94b)

### Description and steps to reproduce [Required]

1. Select video to upscale
2. Select preset "upscale to 4k"
3. Select  AI processor to be intel Arc gpu
4. Press Export
5. returns AI error

### Application / Windows logs

[Topaz log.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15174093/Topaz.log.zip)

**Comment by BelleNottelling** [comment]
FYI: #270 and #349.

Considering it's been a known and well documented issue for over a year without being fixed, I'd encourage either returning Topaz Video AI if you bought it and still can or pursing another GPU to use with the software as it seems very unlikely you'll be able to properly use it in an even remotely near future

**Comment by mujeeb-intel** [comment]
Hi @BelleNottelling thanks for bringing this to our attention. I noticed you are using Topaz Video AI version 4.1.2. I do recall that the previous versions had some issue when converting videos. However, the latest version should not have this issue. I have tried on 5.0.1 and 5.0.3 and was unable to replicate this.

Do you mind trying the latest version of topaz video ai, please? 

![video ai 5_0_3](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/112665178/79b3c59a-8b10-4fea-9d2f-55271d208929)

**Comment by BelleNottelling** [comment]
@mujeeb-intel you incorrectly tagged me instead of @QuintN16 who actually submitted the issue.
I'm happy to not own an A770 anymore so I can't do any kind of testing & only made my original comment because I wanted @QuintN16 to be aware of the very, very long standing issue that Intel Arc GPUs have with Topaz's software so that they can use that info to decided if they need to return the GPU or get a refund on the software if they had already purchased it.

> However, the latest version should not have this issue. I have tried on 5.0.1 and 5.0.3 and was unable to replicate this.
> 
> Do you mind trying the latest version of topaz video ai, please?

It's pretty critical to note that when someone purchases Topaz Video AI they only get a certain period of time to receive updates and once that time is past they need to pay more money to gain access to newer versions.

On top of that:
- Short renders (like a preview) **would** typically work and most failures occurred after about 10-15 min of rendering, however this was not consistent. 
- Nowhere in the [changelog](https://www.videohelp.com/software/Topaz-Video-AI/version-history) does it actually say Intel Arc GPUs are fixed. The closest is that they updated OpenVINO which is stated to *improve* reliability, not actually resolve the issues that have been ongoing for a very long time.

**Comment by QuintN16** [comment]
Thank you I installed the latest version and it appears to be fixed 
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/168619196/c7b97af7-a2d3-42d0-bad6-2585c54be960)
@mujeeb-intel

**Comment by mujeeb-intel** [comment]
Thanks for verifying.

@IGCIT please go ahead and close this case.
