### ISSUE TITLE
Intel 12th gen N100 iGPU stuck at 400MHz after cold boot in Windows 11

### ISSUE THREAD

**Issue by makedir** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#798]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

all, Windows 11 itself

### Game Platform [Required]

- [ ] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [X] Other (please specify)

### Other game platform

Windows 11

### Processor / Processor Number [Required]

N100

### Graphic Card [Required]

N100 UHD

### GPU Driver Version [Required]

31.0.101.5590

### Rendering API [Required]

- [X] Vulkan
- [X] OpenGL
- [X] DirectX12
- [X] DirectX11
- [X] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssu.txt](https://github.com/user-attachments/files/15848690/ssu.txt)

### Description and steps to reproduce [Required]

1. Boot into Windows 11 (colb boot, not from standby or hibernate, better turn of fast boot in Windows 11 before to be sure, with powercfg -h off)
2. do any GPU task where GPU is used with 99% usage at least, benchmark for example on here: https://web.basemark.com/
3. monitor iGPU clock with for example hwinfo sensors: https://www.hwinfo.com/
4. iGPU clock is stuck at 400MHz:

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/6721083/ee2550fb-b650-40e5-8215-0ce9705915cb)

1. Close benchmark
2. put PC into S3 standby
3. wake up PC
4. do above test again, now iGPU clocks correctly to 750MHz:

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/6721083/fedd542b-e960-4663-988f-333f86d57176)

Issue was already present with older previous drivers. Energy profile is balanced in Windows 11. Changing to high energy doesnt do anything.

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

All games, benchmarks, Windows itself

**Comment by mujeeb-intel** [comment]
Hi @makedir 

I had to place an order for n100 to reproduce this issue. Thanks for waiting.

These are the steps I tried:
1. turned off fast boot by running this command in powershell as administrator "powercfg -h off"
2. Updated the graphics driver to the current latest (5593) version
3. Ran Furmark for for gpu benchmarking.
4. Ran Userbenchmark for gpu benchmarking.

**I could not replicate your issue.** 

On the other hand, when running the web based gpu benchmark https://web.basemark.com/ it has been stuck on 300mhz

Tried this three times with cold boot. No standby or hibernate. 

So, I would suggest to get in touch with the devs of that benchmarking website since I noticed other benchmarks outputted expected results.


P.S: Nice username. 

![furmark benchmarking](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/112665178/bef7cebb-c1b6-4fd6-9e15-8c9c28cd2a0b)

![userbenchmark](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/112665178/583b6bca-8c77-43aa-b1ec-fd172fb0a510)

**Comment by makedir** [comment]
@mujeeb-intel N100 iGPU stuck at 300MHz is the same issue. Normal boost is 750MHz. Issue is discussed here by multiple people have the same issue, it is not connected to the benchmark. The benchmark was randomly chosen by be which causes a 99% GPU utilization to trigger maximum boost.

Read comments here:

https://www.reddit.com/r/MiniPCs/comments/1co2yy8/chuwi_larkbox_x_2023_n100_graphic_performance_pls/

https://forum.chuwi.com/t/larkbox-x-2023-nerfed/45224

**Comment by mujeeb-intel** [comment]
@makedir It could very well be specific to this brand of device. 

As I tested my nuc n100 without any issues. Ran multiple gpu benchmark testing with 99-100% utilization. Also after reading the Reddit comments, looks like it's this brand that might have an issue. Do you have other applications I can test to reproduce this? 

Try following:
1. Update to the latest driver I mentioned before this comment. 
2. If it still doesn't resolve the issue, then you can try ddu (I'll share the link if you need help) to clean your graphics driver and then installing the latest driver. Chuwi brand, I'm not familiar with this brand, but I'm trying to root cause whether this is the driver bug and so far it is not pointing towards the driver, otherwise it would happen on majority of the devices if not, all the devices. 

It could very well be something today with the heat(housing) , ram module, etc. 

Also what do you mean by s3 cycle? How do you do that? Can you also make sure "hardware acceleration" option is turned on in your browser, if there is any in the browser settings.

**Comment by makedir** [comment]
@mujeeb-intel Same issue with 5593. No obviously it has zero to do with heat. The problem is simple to understand. Are you serious asking what S3 is? Suspend to RAM = S3 sleep.

**Comment by mujeeb-intel** [comment]
Yes, I am aware of the state machine logic, but was not aware of or seen anyone using that logic to represent sleep states being used by a customer. Happy to learn. 

Coming back, I am unable to replicate your issue. It doesn't seem to happen on other models besides the one mentioned in the title and the reddit post, which are the same. Per my observation, Cold = expected results. S3 = expected results. 

I would suggest you reach out to the manufacturer for a response regarding this issue at the same I run more tests.

**Comment by mujeeb-intel** [comment]
Looks like the manufacturer confirms the issue and released a patch. 

https://forum.chuwi.com/t/larkbox-x-2023-igpu-400mhz-instead-of-750mhz-solved-ram-4000mhz-instead-of-4800mhz/45224/46

Thanks.

**Comment by mujeeb-intel** [comment]
@IGCIT please close the ticket
