### ISSUE TITLE
Crysis (2007) DX10 frametime spikes in driver 5590

### ISSUE THREAD

**Issue by jedi95** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#799]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Crysis (2007)

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Core i9 14900KS

### Graphic Card [Required]

Arc A770 16GB

### GPU Driver Version [Required]

31.0.101.5590

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [X] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/15854965/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Start the Crysis benchmark via the tool using the following settings:
- Very High
- 1920x1080
- Fullscreen
- 4x MSAA
- 3 demo loops
- 64-bit
- DX10
- VSYNC disabled

There should be no significant frametime spikes after the first loop. Using driver 5522 and earlier, there are none. With 5590, the second and third loop will have visible frametime spikes. This can be observed using RTSS or a similar overlay, and by measuring the 1% low FPS from the 2nd and 3rd loop of the benchmark.

I got the following results from my system:
5522: 165 avg / 104 1% low
5590: 185 avg / 18 1% low

This video shows the test with the 5522 and 5590 drivers:
https://www.youtube.com/watch?v=nOVUdJtJ16o

Raw version in case youtube compression ruins it:
https://jedi95.com/video/crysis_arc_5522_5590.mp4

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

- Very High
- 1920x1080
- Fullscreen
- 4x MSAA
- 64-bit
- DX10
- VSYNC disabled

**Comment by Vivek-Intel** [comment]
Hi @jedi95 there have been some improvements in the perf of this game with latest driver 5590 ([release note](https://downloadmirror.intel.com/825322/ReleaseNotes_101.5590_WHQL.pdf)
<img width="339" alt="image" src="https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/114637913/e52ccd20-6cc7-4294-8a07-b2d718e535e6">

Generally game loads lots of assets and data into memory for first run which can cause perf drop in first loop and it further improves as you play reducing the constant need of loading data and assets, so there could be difference in score between first loop and subsequent run of the benchmark and difference between score here (5522 vs 5590 ) is due to optimization done in latest driver.

**Comment by Vivek-Intel** [comment]
@IGCIT please help close this
