### ISSUE TITLE
Fallout 3 - Crashes after New game

### ISSUE THREAD

**Issue by YUCLing** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#807]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Fallout 3 GOTY

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Intel Core i9-12900KS

### Graphic Card [Required]

Intel Arc A770

### GPU Driver Version [Required]

31.0.101.5592

### Other GPU Driver version

also 31.0.101.5590

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/16038995/igcit_ssu.txt)

### Description and steps to reproduce [Required]

The game just crashes while loading into the game scene.

A workaround is to use DXVK.

My 5590 driver was installed after using DDU, then I upgraded to 5592 to check if the issue persists.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

3840x2160, 1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/3d3e8e78-6bf4-4ea9-996b-fc55757da3b6)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/a139c55c-17c4-4305-bd09-e1c470d10839)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/83b7a959-3351-42d8-aca4-691b840f785d)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/05495791-499e-4f5d-89f0-408032e76e0d)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/18556014/cc3a4d88-8ad1-4888-9257-13e6efe070e8)

**Comment by Adrian-Intel** [comment]
@YUCLing 

Thank you very much for reporting this. I tested on my end, and I encountered the issue using Arc driver 5593 (latest as of this writing).

This is actually a known issue, please see this KB article for the workaround and it still works as I checked (game path will be different since you are using the Steam version) -[https://www.intel.com/content/www/us/en/support/articles/000093745/graphics.html](url)

The article shows as "Intel HD graphics Bypass package" but there is no need to re-enable the iGPU of your i9-12900KS (it appears to be disabled per SSU). I tested with i5-13600K (iGPU disabled) and it works with the Arc A750 GPU that I tested on.

It's good to hear that you also found a workaround. You can stick with that, or the one outlined above.

Lastly, please also see the KB article - [https://www.intel.com/content/www/us/en/support/articles/000095196/graphics.html](url) to contact the game developer to report this as this is a game issue and not a driver issue.

Please let me know if we can already close this case.

Thank you once again.


Regards,
Adrian

**Comment by YUCLing** [comment]
I'm not getting a positive response from Bethesda, they seem not willing to fix this. If this is not fixable on the driver side. I guess I can only stick with the workaround.
