### ISSUE TITLE
just cause 4 - graphical issue

### ISSUE THREAD

**Issue by pacoa-kdbg** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#81]
#### Checklist [README]

- [x] Device is not undervolted nor overclocked.
- [x] Device is using the [latest drivers](https://downloadcenter.intel.com/download/30381/Graphiques-Intel-Pilotes-DCH-Windows-10).
- [x] Game is not cracked, modded and use the latest patch.

---
#### Game / Application [Required]
Just Cause 4
---
#### Game Platform [Required]
- [x] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Other

---
#### Processor / Processor Number [Required]

---
#### GPU Driver Version [Required]
- [x] 30.0.100.9894 (*latest*)
- [x] 30.0.100.9862 
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

---
#### Rendering API [Required]
- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [x] DirectX11
- [ ] DirectX10
- [ ] DirectX9

---
#### Windows Build Number [Required]
- [x] Windows 11 (*Insider Preview*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (*Please specify your build number*)

---
#### Description and steps to reproduce [Required]

1. Start the game 
2. Use the grip to move 
3. 

---
#### Device / Platform [Optional][Recommended]

GPD WIN 3

---
#### Game Settings [Optional][Recommended]

All to low

![image](https://user-images.githubusercontent.com/29181120/131778571-35133d76-c28d-45ba-bcc9-39089aa7c4eb.png)

---
#### Save game (*if possible, could help solve the issue faster*) [Optional]

---
#### Windows mini dump (*small memory dump*) (*if available*) [Optional][Recommended]

---

**Comment by hoangnguyen1979** [comment]
Hi @pacoa-kdbg 
FYI, Just Cause 4 is no longer available for purchase on Steam. 
The available game is Just Cause 4 Reloaded https://store.steampowered.com/app/517630/Just_Cause_4_Reloaded/ so replication will be done w/ that version of the game.

In the meantime, can you check to see if the issue is reproduced on your end with the latest driver?
https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html 

Thank you in advance for your help.

**Comment by pacoa-kdbg** [comment]
Hi 
@hoangnguyen1979 i dont own Reloaded version, but Just Cause 4 with latest driver still has this graphical issue

**Comment by estebanr863** [comment]
Hi @pacoa-kdbg ,

This issue was previously reported internally, and we found the root cause of the issue is a bug in the game. We escalated the issue to the developer, but they are unwilling to solve it. Unfortunately, since the developer won’t fix it, there is nothing else we can do on our side to get the issue fixed.
