### ISSUE TITLE
Project Zomboid crash issue with new driver 

### ISSUE THREAD

**Issue by Mika2125** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#824]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Project zomboid 

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5 13600k

### Graphic Card [Required]

A770 LE

### GPU Driver Version [Required]

32.0.101.5762

### Rendering API [Required]

- [ ] Vulkan
- [X] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

![image](https://github.com/user-attachments/assets/12967592-b5bf-478c-a076-101da1543a05)

### Description and steps to reproduce [Required]

The issue ive encountered, have been constant crashing, even from other games such as the sims 2 issue I have done, the latest driver your team made at intel, made both these games unplayable in my experience, so therefore I am currently using 5594 instead of 5762.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Ultra

### Game resolution [Required]

2550x1440p

### Game VSync [Required]

On

### Game display mode [Required]

- [ ] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

![image](https://github.com/user-attachments/assets/e093cbde-e765-46a2-9ee1-59ad5e63d929)
![image](https://github.com/user-attachments/assets/6c431b58-642b-472f-ad05-e9ec9c96d5bb)

**Comment by mujeeb-intel** [comment]
Hi @Mika2125 When does this crash happen? Immediately? On a specific mode? 

Thanks.

-Muji

**Comment by Mika2125** [comment]
@mujeeb-intel it happens immediately on the new patch whenever I try and get into even the loading screen or whatever you call it if you want to play solo or online etc.

**Comment by mujeeb-intel** [comment]
@Mika2125 So I tested on the following devices

13600K w/ A750  | 101.5762 Graphics driver | full screen | 1080p w/ the settings you mentioned | win11
13700K w/ A770 | 101.5762 Graphics driver | full screen | 1080p w/ the settings you mentioned | win11
13900K w/ A770 | 101.5762 Graphics driver | full screen | 1440p w/ the settings you mentioned | win11

No crashes were observed on any platform. It was pretty a smooth experience with constant 95-100fps. Tried the tutorial first then solo and then tried joining an online session.

It is strange that is crashing on your machine but works on a rollback driver. when clicking play on steam I chose the first option instead of "alternate" option to run the game.

I was wondering can you try running [ddu](https://www.bing.com/search?q=ddu+intel&cvid=2f33e00dc7ef4539b3b62a14fd3074b2&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQABhAMgYIAhAAGEAyBggDEAAYQDIGCAQQABhAMgYIBRAAGEAyBggGEAAYQDIGCAcQABhAMgYICBAAGEAyCAgJEOkHGPxV0gEIMjE3M2owajSoAgiwAgE&FORM=ANAB01&PC=U531)? and then reinstalling the driver if you havent tried this step already. 

Also, I noticed on steam when purchasing this game, it shows this application being in early development, so it won't be a bad idea to reach out to the devs of this game for some insights.

Im also looking into discord/reddit if others have the exact issue with this game and havent found anything, yet.

**Comment by Mika2125** [comment]
PERFECT! It actually worked through DDU purr; there are no problems whatsoever at the moment now! tysm for the suggestion of using DDU @mujeeb-intel if any other problems occur with the game ill open this issue up again! ty for the testing to! <3

**Comment by mujeeb-intel** [comment]
haha! Awesome!! glad to hear that. Thank you.

Just a small recommendation when you do encounter a bug like this, just open a new ticket and feel free to reference it back to this ticket, it helps us track issues.

Thanks! :)
