### ISSUE TITLE
Something wrong with TressFX functionality

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#895]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Tomb Raider (2013)

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [X] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc B580

### GPU Driver Version [Required]

32.0.101.6325_101.6252

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build [Required]

Windows 11 23H2

### Intel System Support Utility report

[SSU_20241218.txt](https://github.com/user-attachments/files/18168772/SSU_20241218.txt)

### Description and steps to reproduce [Required]

In «Tomb Raider (2013)», enabling the TressFX feature causes severe framerate hit with the Battlemage launch driver.

The in-game benchmark can normaly get 351 FPS with TressFX OFF and drops to only 74 FPS with TressFX ON. I am quite sure it didn't behave like this with A770. I used to play this game on my A770 with TressFX ON at higher than 120 FPS stable.

Please examine and fix the TressFX implementations with the Battlemage driver.

This issue is similar to [#659](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/659) which I reported regarding Alchemist driver. I think it's basically the same problem. It got a bug ID 14020085081 and later has been fixed with Arc driver version 101.5333 in February, but now it comes back again on the new B580. You guys probably forgot something and tripped over the same stone twice.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

"Ultimate" preset = TressFX ON
"Ultra" preset = TressFX OFF

**Comment by Felipe-Intel** [comment]
Hello @Susie1818  thanks for your continuous collaboration with our graphics products. Always appreciated. 

As I mentioned in #659, TressFX and HairWorks were developed by AMD and NVIDIA respectively, (like FSR and DLSS). This means they can or cannot work properly on other manufacturers GPUs. I can assure you the BugID 14020085081 filed for those was not solved, meaning no specific fixes were included for it in the driver you mentioned, 101.5333. If you perceive an uplift in the performance while having any of these options enabled, it may have been due to something else in the drivers that indirectly helped with this issue. 
If I report this again for BMG I will receive the same answer from the dev team. I know this is not the answer you are looking for, but for some fixes it is essential to get collaboration from all parties involved. Sometimes that collab is delayed or doesn't happen at all. 

Let me know if you have further questions. If not, I'll proceed to close this ticket.

**Comment by Susie1818** [comment]
@Felipe-Intel 

TressFX and HairWorks are both very old technologies. TressFX can also work on Nvidia GPUs, and HairWorks can also work on AMD GPUs. There is no excuse that Arc GPU cannot do it correctly, especially when the fact is that it used to work well and then plummeted and then work again. 

In the past two years, Arc's driver has been evolving very fast. In the process of such an Agile Software Development, when you fix something, you might break something else without knowing as well. It's quite possible that something indirectly helped with the issue, but I think you guys would keep track of the issue and are aware as the problem has some progress unexpectedly and you would try to find out the inter-dependence of various factors.

**Comment by Susie1818** [comment]
@Felipe-Intel 

I totally cannot understand why you wrote "I'll proceed to close this ticket."

A ticket has to be resolved first before it can be closed. Moreover, the resolution has to be reviewed and verified by authorities. 

Now I can't imagine what work ethic and what enterprise culture intel has.
