### ISSUE TITLE
VRR not supported with ARC B580 and ASUS ROG PG348Q

### ISSUE THREAD

**Issue by mchiadmi** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#903]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Graphics Software

### Processor / Processor Number [Required]

AMD Ryzen 5 5600X

### Graphic Card [Required]

Intel ARC B580

### GPU Driver Version [Required]

32.0.101.6325_101.6252

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 10 22H2

### Other Windows build

10.0.19045

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/18187440/igcit_ssu.txt)

### Description and steps to reproduce [Required]
I recently decided to upgrade from an Nvidia GTX 1080, with which I was able to use G-Sync for many years. I decided to try the ARC B580 and was unable to enable VRR as it's marked as "Not supported".

Steps I went through:
- Replaced MSI GeForce GTX 1080 with Intel ARC B580
- Plugged my ASUS ROG PG348Q to the new Intel ARC 580 via Display Port
- Ran DDU while in Windows Safe Mode to remove old drivers
- Rebooted and installed latest `32.0.101.6252` Intel drivers with "Clean install" checked
- Rebooted and launched Intel Graphics Software to turn on VRR
- VRR is disabled and marked as "Not Supported"

**Comment by Arturo-Intel** [comment]
hey @mchiadmi 
Did you enable Adaptive Sync in your monitors?

The only way I was able to enable VRR on my side was enabling Adaptive Sync on my monitor (Aorus Fi32u)

**Comment by mchiadmi** [comment]
Hi @Arturo-Intel, thanks for replying so promptly! 

This monitor does not have the option to turn G-Sync on or off. It was always done via the Nvidia Control Panel. 

I also checked [Nvidia's variable refresh rate compatibility list](https://www.nvidia.com/en-us/geforce/products/g-sync-monitors/specs/), since this monitor came out before they opened up compatibility. And indeed, my model is listed!

![image](https://github.com/user-attachments/assets/9ea10b2b-3487-45e3-b235-18e473541366)

**Comment by Arturo-Intel** [comment]
Doing some research, on the ASUS webpage https://www.asus.com/support/faq/1042713/ says "... Adaptive Sync only is supported on FA506/FA706/GA401/GA502 series (ASUS TUF Gaming A15& A17/ ROG Zephyrus G14& G15) models."

Your monitor supports only G-Sync that is the NVIDIA version of adaptive sync. 
Thats why Intel Graphics Software is show "VRR not supported".

**Comment by tygovanbragt** [comment]
I have the same issue and my monitor has FreeSync. G-Sync always worked perfectly fine but it says VRR is not supported with my new Arc B580

**Comment by mchiadmi** [comment]
> Doing some research, on the ASUS webpage https://www.asus.com/support/faq/1042713/ says "... Adaptive Sync only is supported on FA506/FA706/GA401/GA502 series (ASUS TUF Gaming A15& A17/ ROG Zephyrus G14& G15) models."

Thanks for going through that trouble!

> Your monitor supports only G-Sync that is the NVIDIA version of adaptive sync. Thats why Intel Graphics Software is show "VRR not supported".

G-Sync was, AFAIK, the first (proprietary) implementation of VRR. Later, NVidia announced that they dropped the proprietary restrictions, and would start being compatible with other adaptive sync implementation (namely FreeSync at the time).

If I understand correctly, since my screen is an earlier G-Sync model (with an actual G-Sync hardware module embedded in it), it will not work with non-Nvidia cards. However, screens from later generations, which were labelled "G-Sync compatible", would indeed work with other VRR-capable GPUs.

Is this your understanding as well?

**Comment by Arturo-Intel** [comment]
G-Sync is Nvidia's Adaptive Sync implementation as FreeSync for AMD. 
Adaptive Sync is a standard and Intel is following that standard. 

What I think is that you monitor have a HW restriction that only will work with Nvidia drivers. As you mention in your post.
I didn't notice that those models were from laptops. Will dig more on official documentation from ASUS to check about your model.

Will keep you post.

-- r2

**Comment by EstebanIntel** [comment]
Hi @tygovanbragt and @mchiadmi ,

[FreeSync](https://www.amd.com/en/products/graphics/technologies/freesync.html) is an AMD technology and [G-Sync](https://www.nvidia.com/en-us/geforce/products/g-sync-monitors/) is an Nvidia technology. Both of these technologies were innovative when launched, but were proprietary in nature, which is why most gaming monitors from that era supported one or the other, but not both.

Now the industry is moving to widely adapt Variable Refresh Rate (VRR) as a standard feature. And for this purpose, [Vesa Adaptive Sync](https://www.adaptivesync.org/) was developed, so that going forward monitors manufactures don't have to choose which brand to support to enable VRR over DisplayPort. More recently, the HDMI 2.1 specification has added [HDMI Variable Refresh Rate](https://www.hdmi.org/spec21sub/variablerefreshrate) to its feature set, widening even more the adoption of this technology.

Now, as mentioned in the [Arc B580 specs](https://www.intel.com/content/www/us/en/products/sku/241598/intel-arc-b580-graphics/specifications.html), this GPU supports both of this industry standards (Vesa Adaptive Sync and HDMI Variable Refresh Rate). But, for VRR to properly work all involved components most support it: the GPU, the monitor and even the cable (making sure the cable used supports the required standard, i.e. HDMI High Speed Cable to HDMI 2.1 standard).

With all this been said, I was not able to find the specs for the ASUS ROG PG348Q on ASUS's website. But from the article Arturo found ([https://www.asus.com/support/faq/1042713/](https://www.asus.com/support/faq/1042713/)), seems like this monitor doesn't support Vesa Adaptive Sync; and I guess the HDMI ports are older than 2.1, since this standard was finalized after this monitor was launched.

As for the [AOC 24G2U](https://aoc.com/uk/gaming/products/monitors/24g2u-bk/specification), it lists "Freesync Premium" as it supported VRR technology and HDMI 1.4 as the standard for its HDMI ports. So, since the monitor doesn't support either of the current industry standards (Vesa Adaptive Sync and HDMI Variable Refresh Rate), unfortunately it won't support VRR with the Arc B580.

Finally, regarding @mchiadmi latest question on G-Sync, this is an Nvidia technology. As such, we cannot comment on it or on how its implementation has changed over time. You may have better luck contacting NVidia on that regard.

**Comment by mchiadmi** [comment]
Thanks @Arturo-Intel and @EstebanIntel for engaging with this issue!

I'm aware of the proprietary nature of G-Sync and its FreeSync counter-part. I suppose I was overly optimistic in thinking that my monitor would be able to retroactively benefit from the open standard, especially since there is apparent interoperability between the two implementations mentioned above.

I'll keep an eye on the thread in case there are any promising updates. I will assume that my screen is not compatible with VESA Adaptive-Sync.

**Comment by tygovanbragt** [comment]
Hey @EstebanIntel !

Thanks for the reply! I do understand what you are saying, but I've seen that people with Alchemist cards and AOC monitors weren't able to use VRR as well at first. With driver updates this got fixed for them. I thought that might be the same for me.

**Comment by Susie1818** [comment]
@Arturo-Intel 

Adaptive-Sync is a standard made for VESA by AMD. It is basically the same thing as FreeSync just with a different name.

As @EstebanIntel quoted on [this page](https://aoc.com/us/gaming/monitors/?sync-types:adaptivesyncfreesyncpremium,adaptivesyncfreesyncpremiumpro), quite a few monitors' "Sync technology" is categoried as "initially Adaptive-Sync, and after AMD certified it, it can be labeled as FreeSync" which apparently tells you that Adaptive-Sync and FreeSync are basically the same thing just with different names.

**Comment by EstebanIntel** [comment]
@Susie1818 

Even if the underlying technologies are similar, the way standard protocol work is that all elements must **fully** comply with the standard for the feature to properly work. As such, Intel can only ensure that monitors that are VESA Adaptive Sync certified will have functioning VRR with tour VESA Adaptive Sync certified GPU (or HDMI 2.1). Any other monitor would be best-effort basis for it to have functioning VRR.
