### ISSUE TITLE
VRR is not working with my AOC 24G2U

### ISSUE THREAD

**Issue by tygovanbragt** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#904]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Intel Graphics Software

### Processor / Processor Number [Required]

Ryzen 5 7600

### Graphic Card [Required]

ASRock Arc B580 Steel Legend

### GPU Driver Version [Required]

32.0.101.6325_101.6252

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[System_Support_Utility.txt](https://github.com/user-attachments/files/18189827/System_Support_Utility.txt)

### Description and steps to reproduce [Required]

I used to have a GTX 1060 6GB connected to my AOC 24G2U. With the FreeSync option enabled in my monitor's settings, I always were able to use G-Sync. Unfortunately, with the new B580, VRR isn't working for me even though the option is enabled in my monitor's settings.

What I've tried:
- Reinstalled gpu drivers
- Reinstalled Windows
- Reinstalled monitor drivers
- Reset monitor settings

**Comment by Arturo-Intel** [comment]
@tygovanbragt Are you using DisplayPort or HDMI?

**Comment by tygovanbragt** [comment]
Hey @Arturo-Intel 

I'm using DisplayPort!

**Comment by Susie1818** [comment]
I have the same monitor. I am pretty sure it supports VESA Adaptive-Sync on its DisplayPort because I have been using an Nvidia GPU with it and the "G-SYNC Compatible" mode (exactly the same thing as "VESA Adaptive-Sync" just with a different name) does work.

Intel should look into this case and see if the firmware (V-BIOS) can be tweaked for this monitor.

**Comment by tygovanbragt** [comment]
@Susie1818 Hey, thanks for the info on G-Sync vs G-Sync compatible! I do indeed feel like VRR should work. I also heard of some people having the same issue with Alchemist cards and AOC monitors. The VRR functio didn't work for them, but it got fixed with a new driver.

**Comment by Susie1818** [comment]
@EstebanIntel 

It was AMD that laid out the Adaptive-Sync whitepaper for VESA, and then VESA incorporated the Adaptive-Sync starting from DP 1.2a.

FreeSync is a marketing name that AMD uses, and actually it is exactly the same thing as VESA Adaptive-Sync if we are talking about the VRR over DisplayPort.

VRR over HDMI is a different story because HDMI is not an open standard like DisplayPort but a royalty-bearing standard owned by an organization called "HDMI Forum". AMD started to implement Adaptive-Sync over HDMI on AMD GPUs as early as HDMI 1.4 and thus the scope was limited within gaming PC monitors. HDMI Forum never included VRR in HDMI specifications until HDMI 2.1.

**Comment by EstebanIntel** [comment]
@Susie1818 yes, VESA Adaptive Sync draws a lot from AMD's FreeSync. However, AMD FreeSync still add feature on top (specially the Premium and Premium Pro versions), which make it proprietary.

Furthermore, VESA Adaptive Sync is an industry standard. And as such, the manufacturer must put their monitor trough a certification process and meet all of [VESA's criteria](https://www.adaptivesync.org/performance-criteria/). And only when obtaining this certification, the monitor manufacturer can label it as VESA Adaptive Sync certified.

Now, I understand your point that you are trying to make, where since VESA Adaptive Sync draws from AMD FreeSync, all AMD FreeSync monitor should also work with VSA Adaptive Sync. Unfortunately, that is not how industry standards work. And since AMD FreeSync is still an AMD proprietary standard, Intel cannot certify AMD FreeSync monitors work correctly for VESA Adaptive Sync. So, Intel is limited to the ensure VRR will work correctly on VESA Adaptive Sync certified monitors (or monitors supporting HDMI 2.1).

**Comment by Susie1818** [comment]
@EstebanIntel 

There have been a lot of discussion in detail about VRR in the past tickets #580 and #590.

It is without a doubt that both the firmware (V-BIOS) and the driver can affect the outcome of VRR. They could either break it or fix it as well.

Only the amount of time we need to spend to dig into the issue is the concern.

**Comment by EstebanIntel** [comment]
@Susie1818,

Unfortunately, no amount of tweaks or changes on the GPU's V-BIOS can add a certification to a monitor that the manufacturer didn't add. Even if the underlying technologies are similar, the way standard protocol work is that all elements must **fully** comply with the standard for the feature to properly work. As such, Intel can only ensure that monitors that are VESA Adaptive Sync certified will have functioning VRR with tour VESA Adaptive Sync certified GPU (or HDMI 2.1). Any other monitor would be best-effort basis for it to have functioning VRR.

**Comment by Susie1818** [comment]
@EstebanIntel 

VESA didn't have any sort of Adaptive-Sync certification until year 2022.

VESA added Adaptive-Sync to DisplayPort protocol standard as version 1.2a in year 2012.

Ten years. A decade. You tell me.

How could monitors manufactured during 2012-2022 be "VESA Adaptive-Sync certified" as you imagine?

Arc GPU is the latecomer on the consumer discrete GPU market. It's laughable that a latecomer requires forerunners to comply with a "certification" made up much later in the industry.

**Comment by ValeZAA** [comment]
>Nvidia GPU with it and the "G-SYNC Compatible" mode (exactly the same thing as "VESA Adaptive-Sync" just with a different name)

It is not. G-sync Compatible can be also HDMI 2.0/2.1 VRR and also true Freesync is not supported by Nvidia, HDMI Freesync also exists and they never added that, you see. Freesync is EDID extra block.

>VESA Adaptive Sync draws a lot from AMD's FreeSync. However, AMD FreeSync still add feature on top (specially the Premium and Premium Pro versions), which make it proprietary.

And in fact on my Samsung old QLED (I use OLED TV now) Nvidia implementation causes severe flicker, while with AMD GPUs no flicker. There is something called Freesync Exteme engine and that is _not supported_ by Nvidia only by AMD.
