### ISSUE TITLE
Star wars : the fallen order stutters and bad performances 

### ISSUE THREAD

**Issue by mva94** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#95]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Star wars: the fallen order 

### Game Platform [Required]

- [ ] Steam
- [X] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Bethesda.net
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

I7 1195g7

### GPU Driver Version [Required]

- [X] 30.0.101.1069 (*latest*)
- [ ] 30.0.100.9955
- [ ] 30.0.100.9894
- [ ] 30.0.100.9864
- [ ] 30.0.100.9862
- [ ] 30.0.100.9805
- [ ] 30.0.100.9684
- [ ] 30.0.100.9667
- [ ] 27.20.100.9616
- [ ] 27.20.100.9466
- [ ] 27.20.100.9316
- [ ] 27.20.100.9313
- [ ] 27.20.100.9168
- [ ] 27.20.100.9128

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11
- [ ] Windows 10 21H2 (*Insider Preview*)
- [X] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Windows 10 20H1 (*May 2020 Update*)
- [ ] Windows 10 19H2 (*November 2019 Update*)
- [ ] Windows 10 19H1 (*May 2019 Update*)
- [ ] Other (Please specify)

### Description and steps to reproduce [Required]

- Start the game from the origin launcher 
- Set resolution to 1280*800
- set all settings to medium
- start moving around in the game, performances are very good ( 40-50fps average) all of a sudden fps drops to 20 + stutter + slow down which makes the game not really playable 

### Device / Platform

One x player

**Comment by Saracchini** [comment]
I have this game installed, and tried it with either DX11 and DX12 mode with latest drivers (GPD Win3, stock TDP, power balance in windows all way to left , resolution 720p). I experienced no heavy stutter or issues in the game intro. There's a slight stutter in DX11 in the begining of the  Lucrehulk class ship scene, but I did not see it in DX12.
Settings where most of options in medium, 30 fps lock and Borderless Windowed Mode.

**Comment by mva94** [comment]
@Saracchini might be better with dx12 but game isn't meant to run with it,  was there any issues?
I'm going to make a video as it is quite obvious, I'm already 4-5 hours away from the beginning of the gane

**Comment by Saracchini** [comment]
I see no issues with DX12, besides the Origin overlay not working.  I see less sttuter and  a bit better performance with DX12. I did not see any game-breaking issues in the intro with either DX11 or DX12. I can try to run with unlocked frames to see if it is more evident stutter. Perhaps the issue is in a point further in the game ? Unfortunately, I did not play the game that much to see if there are problems later.

**Comment by mva94** [comment]
@Saracchini yes try to reach higher fps to see ,I'll post my save game for u to try it

**Comment by Saracchini** [comment]
Performance is lower in DX11 (30fps mostly, dips to 25-27 in cluttered scenes, max 40-50) but I did not saw in the intro any gamebreaking stutter. If needed please send me later the save file.

**Comment by IntelSupport-Arun** [comment]
Hi @mva94 ,
Can you please run the [Intel SSU Tool](https://www.intel.com/content/www/us/en/support/articles/000057926/memory-and-storage.html) on your system and attach us the result?

**Comment by IntelSupport-Arun** [comment]
Hi @mva94,
Does the tool [Intel SSU Tool](https://www.intel.com/content/www/us/en/support/articles/000057926/memory-and-storage.html) work for you? Please attach the result.

**Comment by IntelSupport-Arun** [comment]
Hi @mva94, Would you be able to run the [Intel SSU Tool](https://www.intel.com/content/www/us/en/support/articles/000057926/memory-and-storage.html)? 
It would be better for us to understand your system details if you provided us with those details so that we can take further necessary steps for you.

**Comment by IntelSupport-Arun** [comment]
Hi @mva94,
We tested this issue in our labs and did not observe the issues that you have reported. There is a new graphics driver version 30.0.101.1994 available, and I've tested your issue with that driver. I noticed no frame drops or stutters during my play-through of the game using the latest graphics driver version [30.0.101.1994](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/30.0.101.1994). I have attached a screenshot of the game, taken one minute after starting it and 10 minutes later, for your reference. It will help you gain a better understanding of our issue replication results.
![After 1 minute](https://user-images.githubusercontent.com/91881865/173495796-22fa3f54-0d4f-468c-9e27-9366347fdafa.jpg)
![After 10 minutes](https://user-images.githubusercontent.com/91881865/173495833-c342cea6-0681-42ec-8655-cb2641134b47.jpg)
The average frame rate is 41-43 frames per second in both cases. In the graph taken after ten minutes, the frame rate does dip a bit during the game's more graphically demanding sections, but the average remained at 43 frames per second.

You can try the latest graphics driver [30.0.101.1994](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/30.0.101.1994) and I hope that will resolve your issue. It is recommended that, if you are still experiencing the issue with this latest driver, you contact the support line for your device manufacturer since the issue does seem to be device-specific.
